---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paperless-backup
  namespace: paperless
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paperless-backup
  namespace: paperless
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
    resourceNames: ["paperless-app"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
    resourceNames: ["paperless-app"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paperless-backup
  namespace: paperless
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paperless-backup
subjects:
  - kind: ServiceAccount
    name: paperless-backup
    namespace: paperless
