---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-secret
  namespace: paperless
spec:
  encryptedData:
    rclone.conf: AgBbLSb+ynCl0cc8Hzc81AWkTmRpbhwicbZangHpMun4kS+ztjUk5ttWoSm/3JXmipPzD1qA874WKaaoRZDbHXbSSy3DUESxK12bShSjoXEO2KI74Mb4NBSfjQu8hZhQ5z7ROhvugx8l3753qClKP2KILt8iPuW+AXZ5eN/jgVnu2+eI6kT+XCBhQ/3+u2Xoz5TsnI4un8Cfru/EbOZN/42G4vFuuv+hUPSTwbsy11OehSYN9TsJMZak3BIBIvg8ylz6dEjvJ5WNkEmAVpvCUwfbVLoFj0q9xKpe7TOTJQYG1kEQNr7/gp8861FQbprn7zfREj+f20BECBmh5CUHv9VYQrmie/tvVEXo5PffmgtfsCJdKebZqRvDEGMEZ6NedRMBN2tai7yOD6+eeNroLojjyfkqlL94+gwfrXmBenEcDUAlQ1VhY073SbNHR0drGsyAN6E42EJSLJqkRNaefuG/C2L50KtA99EHVd0iMJ3fw9l/Or66o7qzUNnHUPDnATKPlWHGXmnGw3zuYCKZ3+JrHwG8uEIt8uSbY47ybamnBPERvVhygrsjLxEuwWHnKj60062lwc3yhBveIQJ5Co1GMYtWTqoUbuezcSsQtMmV6mNQmlm8NHagVRJ2K5ORWmeYPlxEMJwkP/d2JoXOIdwNDsZuOGsKpkTMhDfd48BPI4OUO2zBzgZbRHoPAchWjnqfNCe8KITgR+NnJzOUYqH4b4Bbwu7AOZ7aoQqeE4UviMtr8uP5hgqVue4//ZJx8oyJUJCou750Qxws/t38UHrftju1ybz+AzFmVriIu68zrV3IsVpvxG6W8574xeJ+Xy/O9FDpsdr7cn63zz196ifXc03Sf0gVjRqsFCK4TqJPEPTS4EZwn1+I4inII+N/vSEgPNx5SuCGSinKI8Ayex4IiB4N/iRVvI3muegOHNpWvVqp2UHdnHr6SwtBYXzm43fZbvm2O38lH9eq1l+w4HGxeNcdMMuzAUaNdMuBS+Lb8zYWdjp3y62sbIwbT+P6BPE/Mb9po4XiRcvZLj/eiNlEOuyKH1WwYqA0Sq/wb2RhF4yxw2hE34vXKZ8UACPmFktkVYCHdWeO2CWkApx4Wasu29ERdFLKW39OkAr7SRhp9vn636tJZ8CL3mtwt92uxaRVxKFC6p+W3t9yEqPaLtfrdn7CleGCcFTMXxWjjxCwrcxsglyMupW9rxE+LFtmUPfTppWl8/XBbya+Xb9PwE5hFtn3vwjgGKCfw88hHSKICffVrLEBstO7NMlSp8JynNaphmjJ3hvyr0rrvFcSTVUdZmb07bXT3DuxRuu47/u0qoke/8PRoWBhCxG1f1NBvZznZDjLZAk1yMff/IjfDDHr9TjZiZBpM5HPt0xefw7BW96/OwbQVa4Ps2OGddEG70PQAzco9QY69Vy1XA2beZX4tRqB0cTEG1fEJ2tEcq+L8202OgVhj2vyXJz2YTsC4DqGrYGDO63IiJzQVbFiUiOygQRfffeDx8XRMH6L2CSVmCuhkNmLKsgJmy+8BVE0
  template:
    metadata:
      name: rclone-secret
      namespace: paperless
    type: Opaque
