---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: paperless
spec:
  encryptedData:
    RESTIC_PASSWORD: AgCz1/FR/QPShvzle7whvkU8qZALue/QFho9x7awQvRYq+rcg/K0WEES3xfEZKw1DaGlYw6/1tPFgM/e3yxr+bMOaxttHLvO9zhDxwFOZp44k0g/HGkwRdB5hU+Il+HfnuvTE4ZbRsWpdL48jCA0MWXDGNX+s/DMhrxyM5KbCiv/CdmKf1wUcPevumEUTnPFBU30xnsGEFnv5nn1ZKuSPWxWZWLInbk4EyydPn1Zx21GEdnKc2AVp7rvtQ8bYIIzd1tvJUtf8J7UUY3t3etjpAmO/4TNmWBKRXc+pyn01pQVkT6Vyg5gdQ2L1TukZqVClMAQRs2i/8iV0yEOkpts4yBWBGnTGYgmXdAovPvtR3hxrCY54xcvycIRpfX1GZQ4J5F76LrASw+wvMwXVpyjbEAYYLXItgfkgJJg96UyaQY2pgqUK/28PhqCy2aCKrNXKqYiOvEcMLug6vP/rEcYV9HIdDQohDATFh6at43K67P/ar4v6btL8cFgFlQWLbTEQLZrIYBgjESjdcEsSOXHQORul6ZdeO+q+cMVydFfM47WUqIvJY9a5DbT53F8BgHd7MfJq+TPDudROo4u1QhwsNzUmfar89eDKOuxhI0eB1t0TD39osX7HZwX5ogG8LsXuZMb6XZ7kYVq8WnQDbS1yJy8QA5q1V2tItcVtdDoFxYQow7GEQeY39GTTQHakqqLblyAO/Jq+17ac4LTrhH52uAlOq6PLbkOVVvaIt3BkiteOcA=
    RESTIC_REPOSITORY: AgAjv7iD4J72+007BqlfX1pmETSzvFdxwFrEwRSA0cBUVE7rdGfIBrWJtmfPv2gA+dCklPPLTHohU7WYZGOPL5ZoIemf344AEpwkhGCd+sDwuMBAvHIxJbl49VxiUT8EVDleQa5K6RiPyO4MK8qkfkjuNv+NXZb0EnlfYE/bVu692TwXf8RweqiIynMVROTyF5bj/V7B6bdBKO5OCySwIkzYQx5r8lwvOzWB4fbyMQec4G8tFSomKmStpt7ltWgesh2t0fJkmq688ToEguNRecL2vIRd5xZ8EafJ1jRDK93nlYEe7990qdi4wJPyTceXcTDygdqbDwyeEPuL6aAX+ElX42EoOBVHLjpKPyqeBRaxbPnpghoPKzYX3Yna24DOlq2/5MH/H2b95N/dlUZ0cISI2toVUogNveA0tITQ3YWxPE7TY84uA5spDTKabkSe1NoGs3UnVz7ssxjoOnGhFYs9Hal8PpI3CvDZ6SK7lpWDfKv32sfO0rzgMJ02w5YHpYG2g/r6z0HBSzFA8DK17S/vmNt/3S6ffUM1iH25VmFdLArAUNtl75slZJo1XJ6MR1+MdpXe49LTDDh+VJMAzVnBxuQoimtnGb6KkRpt29biMbkAyeGU7G1Y7wag8e7lU46ZSAuaE65gBCaCGePDf2osjtY76PX4kwwpClaOU6WZNWCn0PINUFg3eDMrDRrxmmMsYcLGgg6AB1KPMbfG9aVcEKzXR0RSrqO6jFbcKiPa41Fow3Pr
  template:
    metadata:
      name: restic-secret
      namespace: paperless
    type: Opaque
