---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joplin-blobs
  namespace: joplin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
