---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yml
  - ./gateway-api/ks.yml
  - ./cilium/ks.yml
  # - ./coredns/ks.yml
  # - ./metrics-server/ks.yml
  # - ./reloader/ks.yml
  # - ./kubelet-csr-approver/ks.yml
  - ./spegel/ks.yml
  - ./sealed-secrets/ks.yml
