---
.global:
  shareHost: &globalShareHost synology.blackcats.cc
  shareBasePath: &globalShareBasePath "/volume1/Kubernetes"
  controllerBasePath: &globalControllerBasePath "/mnt/kubernetes.nfs"

csiDriver:
  name: "synology.democratic-csi.nfs-client"
  fsGroupPolicy: File

storageClasses:
  - name: nfs-client
    defaultClass: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: false
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4

volumeSnapshotClasses: []

driver:
  config:
    driver: nfs-client
    instance_id: 33823a5b-0d7a-40e8-b931-92a03b1e0889
    nfs:
      shareHost: *globalShareHost
      shareBasePath: *globalShareBasePath
      controllerBasePath: *globalControllerBasePath
      dirPermissionsMode: "0777"
      dirPermissionsUser: 0
      dirPermissionsGroup: 0

controller:
  enabled: true
  externalResizer:
    enabled: false
  strategy: deployment
  hostNetwork: true
  hostIPC: true
  driver:
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - SYS_ADMIN
      privileged: true
    lifecycle:
      postStart:
        exec:
          command:
            - /bin/sh
            - -c
            - "mkdir -p /mnt/kubernetes.nfs; mount synology.blackcats.cc:/volume1/Kubernetes /mnt/kubernetes.nfs"
      preStop:
        exec:
          command:
            - /bin/sh
            - -c
            - "umount /mnt/kubernetes.nfs"
