---
csiDriver:
  name: "synology.democratic-csi.nfs-client"
  fsGroupPolicy: File

driver:
  config:
    driver: nfs-client
    nfs:
      shareHost: synology.blackcats.cc
      shareBasePath: /volume2/Kubernetes
      controllerBasePath: /mnt/kubernetes.nfs
      dirPermissionsMode: "0777"
      dirPermissionsUser: 0
      dirPermissionsGroup: 0

storageClasses:
  - name: synology-nfs
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs
    mountOptions:
      - noatime
      - nfsvers=4.1
