---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: degoog-secret
  namespace: degoog
spec:
  encryptedData:
    DEGOOG_SETTINGS_PASSWORDS: AgA+7//N2pVAZPvUOLYHj1xFp//MIqtsj/r7W0AsKtZoF4PII6Mu24CDP/ZvBOERlGS5rjZHrD6O8TabFNSdcaOPgLzmrkvvSC9d68fczmb5DNql9KMTJefPD+uimr+vWVFxiWDvCtHYkpTKNSplStvttOgz2S39G24BGDd0a0Iwr4Wz+9MkIFsVtJmicqCkYbFOIPa7N7iKU4CPaY6dO5BZLXvQHWhB6G1Rgq75axNTv89VQ5qcif6dznmIdq61TwKhL6iQj6VeviANEnD4o5+dGWKohCVvkKI6adWErZDQB4XxcEiwUBzJnaGIEchwv6ZlE1x7lABA+YAo4Wj4m7314MEPBbt00SC+471ojPAadSLCL0ggz+rCO6rjXl6+5HUzaXIiZPGy7NrMfh7S+mfa1viykDIhjwEN5UJGrc+ALhykQHfkAvCTxlmAcnWMKddDcEeo0YRZsGNDI/rwIxJ9A4xn579yWqY9p+bQvEhaM4QU0fjmRWXDmU33hhIblxPg0SExBnRP0BazEu8AoL+Wzsq1grv0N9SYVBVFtR/gYOahpcr+dtO+VkHKn0j26oQD//a8D7KTMw5bnin3rZ69xdHuf3O9kFHaXfRdbSnj7osQyF+5ahtWcBUCMrj+WDEj1cu72qxzGi9Qm6pUfFAgRzzY1kM0NpZdnTvoTVTKBDKbjUujDMbbd+LZJYlhda8rJztZfTIiJg0=
  template:
    metadata:
      name: degoog-secret
      namespace: degoog
    type: Opaque
