---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-secret
  namespace: monitoring
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgALTyHZwOvHh9M5LeN3cCz5q5lgB4hYt8IgDbMHt0yTmO/3RhKB9i7X1XUmWmx3Jd2J5K305RaFDDBjyWJjeJSSENfduqe+uA74MglzE1hZX6UARQr8wPnDnZuflBzhfIPEg2DdRvbumdh2Mt6EIuHQBDTg6BUlvR9MP8y4n0sbOJdWmKge9e8VJr8N2nwnaJdq2ngs2ClItcrjF+lMgPPGJ4A6KhoMlXaElJU/qMUp8xUMztsm1JmBPCycKb3bc0oP+LaV5r3OyeDlF8Dqkbbbe1ns5BT6jeaAMxYfIgYf0KFOAns714CCeAKKlNDkDhPPrz9ekj1bs/1y6EgLnBfgmJhi3tSxbqgdTffhl4XWI/HUcMhox1SJjKQnHG07Pvl9x+7T5xWk0QLLNt/rzKre8OVJVJGp3CWOXfvEj+0NK3odeKcC40XlMIbajSww4qXkOZKa2dI5xtneTgB71IfdNLecIT1QD0Kb8IsY+QqAu97y0VY2yajVApyJNGduJQ3S7A4sfCwZTMHo1iQ6z2cro4AcySXaDBI1f7dDFCc82oCOVy25I/aTJiYYgQbp9AB1p/FFxGC4ilWt0LDNqHYdxP9p4InbVRaAyVeUT/HE+NtkXoLmPt1HVqj8nvdnGXVA0O6bfE9mbPbQm4BtEMkhXDVGg281gWjbQp2cxTYqNT4W6QfkCgLpx/dXdfRty4oPrYsxrv/nmpIlwvk49zfE9eMHSEkVdUueyB0aBKi4aUruWR07ZGpKEvY7FgTL
    TELEGRAM_CHAT_ID: AgC4XLA+zJTW0rUvnssP+zMieDRTXvv+Kpi6LIX7nWjQefe7+Dex6qf3XIubTbbvomqjD3O635zbzZm6Ph62uXiLPfhbaD38GNVzeD18Gzv+A3l4sT9DwQzX3eOET4WvN0Vz/53uD0c7RdOFl51DPmAZsS0FHQFD5SXn9rqngBtJN/bJCeIwSOqeM+chUjEnPG2WZtUBpUJ0Zxc1buFUyt23jguj219qjuD/50MHv/w+FXik9j5b9ZQoq6MvsfSnP9JyMpb/Y++SZDG9MSPWrKpnyKN0bt3F1RRTlmSoTXp4k5cGL/2InPPo1hBm/ta6jzGqsZ5XwdeluSDcM/v9F6PgsVD2b6mc1pPUmtkHPWlwVGn+1PNHrYvs39FySiihSuXEksFod2ya3kZFiTmj0Y1wnwtyzWBRxUkEU2kKNswfxxcrZuBG/GERwBWZdQgz1tmimFDQo5OAaobfYr3DyXsYQHdB2eukLL5c0OO5sfveb2aDx0spVsF+4Vv4WcapfcFhKQgn+wCrcU4pBrqY9Fb+In2FZPbvmhzD+Wf7awpRwDW43q8Dy2lnkg5Tafj/mt4zK0CcJ8iZEmlyeVexu9oQ4tE82vdtejPZ5L1OvDorYt21ENpMR1GCpmNTPE/eB3+t7eMW8Yku0nKjbhU4dau7xTWxMs0kEACYkOeWpRldSMmN+000q1jGodW2WLUEuhXUYBHBcc+A+aNV
  template:
    metadata:
      name: telegram-secret
      namespace: monitoring
    type: Opaque
