---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yml
  - ./media-nfs/ks.yml
  - ./sonarr/database/ks.yml
  - ./sonarr/ks.yml
  - ./radarr/database/ks.yml
  - ./radarr/ks.yml
  - ./prowlarr/ks.yml
  - ./sabnzbd/ks.yml
  - ./seerr/ks.yml
  - ./plex/ks.yml
