---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-secret
  namespace: immich
spec:
  encryptedData:
    rclone.conf: AgC5Wuq6lZUtC786hCgEPK24pPLhDfXpJMDUX7bTxS0PGx3BMq9iflepWBpkNWehHju7eRodKJPhQMrOExgSYVPKhRoCV0l3Quy+M5PJ3mFofeEPcZ73R3HtXIOAiKP7dOLZnjb+NYhV6TslskmMMigpSfy1lycepgBrrya8ZeDm9v7bBvRsuGYhwmgd4M/Rnv7DpVG++36jvqZArtBg9b0o99t6MrNWg2E1aGZ+fZf5kiyQdbNB4Up7ywJ8yy1IAsH/WIxDnx9mB8DGmTL3SLKdV4R0qZFaBCFV3LrJ4xkw/9ZddQICJQEbR30eVN58zWIX6/k0JkyRJQgp7I9/HHRZEiKWD1ddEMkrPp5aTw8xXcIw2x53nvfOro5UdfLwE6xbgWgTG4oy5aUea+cM+Lst5q7Q9aUi7og4Q0vW1fc6M4kVrIoiyobLt/ise9NMjfmDe7q/Qd9Foaeee+MojzaxN69hI5GpF43PPpFa59ugp4w/dGglCYHMLFt/2KCKr/NEKLHl88VuA1C88EgX8rkGlV4D/zbTtglPN3DLdxTTk7JCxA0zShBgLfJq6AykTK6wLunHfeSUfEw6uBHQlRfbRwqoKqpZjhxv5ww+kS+yapE90nwua5uhRFKiboDd945lpa11YQKWiQqi9Nnqc0to4jbgL5FYktMjzQzRCNXVcgLBgm26lZbYfwTHFCxTgm/W2c2A1qUkiCginW8nejfTr2Z9Et6+A1T6Gl/2taGrBQG8VKyr5tv5FCwEeNJapytAZ2+nLHjXMvf13W6OkeYTFR+TfyHLNc91HbcA5YjmvNKt9tPO9wt4m2S4qu3jkApxV8WT30ObWFROWY+CgoPSZnjYG5+kJ/HTzd/zQqrNVm3EK75XBjjZZmynXA/wlvAipJ1DSCeyInejvgH+6aXZJ01Mt3hOEeHW+VWw4u6t9Q/bqyWqd9BJUHPKRQzSmJEwqPcwiOqk5TGB+1ZuNVV0iYADZLqJ12d6ZrNOQs7MSmJkLBDippc2Pw5c9MrjByJFQ5NpbNlzmVtMWLbhVmsgau5vDTVk/lBPfn/P6aHjdzpHfnJT91CKBd+xpWu7/2uRXvDMNUIN6rM3qNhqJI1R1ReqFrVcut2nTszUttFW9uttPYErC1mRydfxb5CksMX7BxgN5SLpbk7LdzWP2jO8s0hWFrTQitYou8eKLWRA+Pf1YDT2rZ35V5V6sZ9ROGatI/5a+XkkIoLLbJPZ1Xztwhd1oZc6JhqpFn/WO4YFKICf6w+PMQFKT4Ix6KY+VHQMwWMZuORmmGKTSnbwvHSqWq6NICyANq/8hl4Bhp4JwWE46h4/rBAKiYTe+Dbvz4RKQ8cHTPQCYYCdQecIhlnTSDOGvhx+9BFwx04NaBzdGyMHB2G+8I8Fh5YwaLfYYer6hZ+TykEJQ3slbeL2hQyHEcMTgHJldIKfHkpaxaUaWhCnBvW8/r0tBvtsjO5Elgfj2bfRXVuBl29DRN3f2dwlH+tl6Xiw89KH/g67OAGfX4rfXTVmXntuJQT0
  template:
    metadata:
      name: rclone-secret
      namespace: immich
    type: Opaque
