---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: immich
spec:
  encryptedData:
    RESTIC_PASSWORD: AgAlxjQRh0yfI3wFlrQ6Mu/P1KC45BiJkUxFb9j9V+Zwm5C4KZpSUh2Zl/wzTCRcv8QCbsTHEiXSQlF+ET+Cfl/hTSUJ5UMqQa3/X9Y659RVPoHiKXqcX0ZKoZeDb8jJ4IHHFhMaP8GGOcjuLWgJHksUoG912qIUq9ER8RgAc9+eM5LTVai5ddd4O+eoYOwh+ZfARS0qdp1H+GRslrJkbbzEOV0JnF3YCWCQnofmUayUS6aUaQycbvq8DAAJr20IWJq9UI1otfr7xoF7Vkpx2ZaDzZITBDWSoml0lHSKFPKsN5MGQAP1d7uh43gSJNKIe8zWXSRD4zIIu3aPnj4jw/7qMwDRz49ggyJb2V/l2oN6a8u+N+fVx7qsrc63PgQY05rnXDZXgM4Apm3fHYvl15Z1ODiHeZuHKtVBaq7MOKm1CYw4P+kmj/hp7xzETidSM1MiwH/ujZk1EYuNsitKuorPohgGAfoUk5Az3k0biK9la7EjWGRE4s2LvlsVasHd+4t8Fkm1t8m64XQP00h6DOjXvEWJ9LNIPx1IyQXSSJ7MUPYXnYTlWQEHYqFYxOMUJ6BnKLC0vFhcQTVhbcp7UG6jFuqLD0Ecnwh3NjvqPNofoeu22axOC8sLbWXNIe/rF1WhytDWEKinFNyfEWUDe6wwWSDQbx5H2QURoh9H6etTXjQ9UkbywrUZp9ibtBMagL0nzD+aihx2hh/9tcqDa+3hu6VZJFtBabXm6hQ+LLrLI48=
    RESTIC_REPOSITORY: AgA1OBxSxhbkq+/lOvk9zWd5Tz5mUWkpTc51Wh/Za/gyTVvSb40u4OQfaZhPyOXsAPSjcs78UcXtVb/GwrJBa9GI0VekyofjLCcDIijf9TnKAnJTJu6R93FBVKGKM1TKRu+l9i0wOUk4VqNhyM709i8z/y0kgOkbIJz/2FbcKaGMAi61nJxQ15xM0zYG5fiS4Jdo6B+5vdLFfb/X2L8sLPc2pSaNxZZjpIizDWINS/tSlvIkp9OQVr+5ZRXGegP0ZMQh/XhNRfjEjDS5aP24ymAChUOTiOyCaO6xn5gnJr8calq+V+MtKZS3qcVJrmb7BagQqfW0js4Ky0XgPOFH9HFvwgoyaGh1txOGA8fzPO68j6qrnpZfTjtDWnt1RLILBe15jwOV7FSwT5YR1Egt0MvGXrTgWt+eovXwtyM/uPTbyhwhL24Nsdy9oq0KTF+XoBcXHzLMlUx5XU1J6PQhsbWvvwQQ/CWDcaHnmsyRqod0ZB4qa1Y37BNLONODhiNhxgTezBTsNMi9WWavx6SyXVN5wrVZgqjqDTqRTc63aKkkOyzlYUQomnDgFRKo7T/bvJgwJhidcstYpmfHJK82wSuLaCDpkGcZGkI+Ty8PWnEp9VyR0O3LDE3biKVEMM3P+gZbn3QHq5+MepZNyUK3byleOUahH6ktBEpgqkQVnCAZfLhV7N/KBLXA6AwO4OHlOWfbYdk8U7GZHE3ji4jhGUBD5z8pG+tCH6wbdjrysMncem/w
  template:
    metadata:
      name: restic-secret
      namespace: immich
    type: Opaque
