---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: immich
spec:
  encryptedData:
    RESTIC_PASSWORD: AgBrzKaIDndjDrJFMIobbvLkNUXM76fWmAaBWevF6PgkYbFlCACa6apuL6OSTgKwjpUjvhtB0YhFZ2rWGCRudAvSfp8eGSSQ/rFq5cLN6WYb8gbmxyrc+vqKGUjfPtXRP4FuAQ7A+51jP566VtAoGnJzYWVLJAMvk9bjQmadXkN/2y4ivI2uXNl/zjuOWIk6A3KD5LOvyZ+VW8XvsGOfAGUov6xI4CygvdXBleZYj9oJfFcxmhbDTxejGL1Ns5tOAghGgD2CZHmBjoZPATuWXVXFR7SE6bnlBvWeEqaEPtDxHi6Rn1tsJV88ShDTAX07sv8UKzIMdHuGPUz22qQJnVLJyEIeA6CL1WeI6+Y/KooIoO21vBZbzgT3kzf4niaAT8k5ImAMSHqznIoq3YnSFfSWhqHfoQEg1CJNzvGSrtKX60FW0zzbmyHQtPDiZx7hKZa4AWeeV9L0p8YSdN+N99IO9rmv8m8QVWIROqC0anQrb4o9ptBQgTmfet6ETaACN5i/xXo3d84MkNASuqJ6EkTb660ODmTvn4+oLVXcf/IWP+/eh6Z3jBUiikfhMxTdjPp8F2d5UEAv3lUW3MU/Vd+4oJ0tCndhhWSI8WcmP2/a3PkPZ54w2MqUxd6AyUYDAYsTv19Hy50r+cNKLIOIkVS0R2s/eMUX5m/VvbVISS9KrBhiUHjCTJiwNd09sZJLt6Ka9eJI5DIZ6MkZ+RDPnrDqOVR/y92Gsj1GeR5i3fhgkII=
    RESTIC_REPOSITORY: AgA/vCfMFzxr2BVTPRorKTlRB3YXJO8VdOEoRJ7D+cUM5CzplfNjIWzzZd9HM/N41dyn2GxNgCTS8SwSdT7xbIe+kEADkfEY+g8hcam3zzlBfDD8AGnASqb/L0PyBTIbBkGIAts5N77tB6i9ITpZ1oS7U66KTv1oUwnX0ICgC6F/Vnyo6vQHiuuIxEuZfDUY0KzDG1dtEoXY+M5E0yUq3wywCDwh9moqXnR3/bC0eatMOExv+cYuK5n6pJbiak4BtWHyRSVALeB557NODEO3Hx5gJ3yMALVc69cBwS2N0Vl2kBmwV1LuHO7vRO2qJeehEHJiQvxdLamTa6zw7D2776NYoDszpuxoAJ7jGatVczAvHRUc8Rzbs5ZIQfpshXj7y+fWfnPzN/thnA181/mlqf1EYkmMKVyhdQgaUebCZDxlVp9IpD8X8y6bHEl/tnxp/a6RXKPKXUGpq3ODUjfkzSLjnbBhgcfCZv5Tlc0li8yC6j6mAP1ByybXBV7XApR5uvk+QGWgGdk0BInie1HQjrnjL5fUbHrgd9QpuH7wGMO5s7XT96fcP0MRoew2guWCPrOdp2DIZIEWrqpe4qLjkwblFWITvqOTjiUXtmx/5PAusuWkFOzBHkcGke1qQzDFFKN1ex5fjoEWdVdeRtTMKuvS/RfwoX7a0NQt5TJnZTCv9D/sWJh7VfQhHGCx5gPDw+nEF5TgFdhqZXaI7mm2NEY0QHMBQcg0kQGt7Ko/Q0FGzA==
  template:
    metadata:
      name: restic-secret
      namespace: immich
    type: Opaque
