---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: immich
spec:
  encryptedData:
    RESTIC_PASSWORD: AgDBiinqXwRNVkHNsVV653lzGhryfdD9+oDADXzBiKST0LuCa1b5GKkbCnRjepQTYa8GqzlA+r6wlDZJ6yAxbA+Wf7UQ6n08MaBhE5vimZ8qLBFilPzeDHXQ89iYuPIyO+N+TGtrqzSJhbGN+ZiXpMg3bl5Am8JgkWCeBuVGwdToNbb0Ob+oIBvQAWKj1CsGN5deYEhp1m/zxMtCfZcf2uEer+2hnLYeoGax50GoM+VxeBxZuZz4eaB7Cjpao8jGx4EfatJC9+4mBFVaPmHnMiDn5bPD/p9to2FJ1veIwoDdguRQm5BPvbhb/ccSLGSn64qfqHNYqxF0HxKLKUX7+P/8xxaQChH4YQpf7PeX0BILnX0CbKGStt/IKMjdL1hSXLy9mCQPL4U7TTWfvGZV9HxQt/1n/n1T25t7ndecjRqIpFyOKQ/guaw36t3uOYsbJM9Jeg79j/hKRTf+DkDiyOwi3f2BHNI2NB/lfjJ1BT8Kpg0b3yJr+ADkeeWCy+N2S//jEkWmdiWVkdl5Z7GYkifcXQcxZaCnksPcHwMjD3bmY+9aGjICxoepxznMBPW79D6PgPV8NXdFHyYQikAv83XTXrLz++pLFtqGUX+5cxz/ZrBFNoPKfj4W4sXTxMK0ZEUXgRnkDSz/ECa9u1QWA9RLjQVlC9Tg2QZOObo06NU7FvBDZLtmJglAAPq6CTxmG9E+rKi0gA5b4OmxOzZItw5AAzSlQEFIzBg1ndB1P0WnRHs=
    RESTIC_REPOSITORY: AgBJujfZFuDs4T0tS+3myeI7cnDVUBvxAB2g+FfGAkDrZhvJxh8Hxo6csJ6SZnexvrDngGyKp4KBLbkoT3VrdJlR5Z3TCXlbmTX938+ghcO0GkIbuRwHDQPlUcBcME9SGrSkwWSPZX6q09iFmdN3B1zMMGalDYzkrXRUIcdq5MeV9Y6nq7vQsR6tnEbH1Px+anqWsGj/YTPlj9PxgXl/ePjx9PHUalF9mSI+lA86djq9eKs85su7M0VJyuk7sgFEIIy1ihByIacOfcC0Y6wlPp/MJ7yo8gbbydqBhzjJYx1x+p3HRIZ6SUyiyOzNNt01AFob7tgONP4YK5TtbkQ0O0pa7LvsqkfQKV1W0fLJ0RTrk5s90sL4IC0KcWsqDg6KT6DfrCv/7F29hk0IdNF4pkOW7S0G06aQCNY82OOfqWCkfa+efzJFmGCCS52y8gIAiPnjS4774WIh04zCn7ExLz9/QbyHP0IMdx9OJhFmh0xdfBSq51LLvoo+wpbAhCCgCHoMumRKLs4eBZMurYNghFRJj2vcaglUSQatXWvmiTtesNOEAo/nOLvYYKoocGmhq/86j9laoxeL8IZVrFH4guJt/0tfMwj0baSavinsl0klrp3V0yhXR4JiMv2j4UGsAOLn3+ipkSUS/aXUMAjp39CDXSin6pq9lcWFvF/M5n6deeEei+UJqqRldJRldyN0HBLhxxnoaqij64yg3Xav6K1yNSka3e5zCsj/3g==
  template:
    metadata:
      name: restic-secret
      namespace: immich
    type: Opaque
