---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-secret
  namespace: changedetection
spec:
  encryptedData:
    rclone.conf: AgCF6ij7WZXl2w1sJJ0cu+ekkSYQVbBzecqw/GWJKDtNYPTTlSH988kwl2NbBP5DDeucXtxr61aJ2Z7kVsTfJR5y+Ksg0mws9Hv5R7c/XioPl8orKx8Xf8dhtfE9TDehTAZywEueT24rSdk63AAiJXU8+05VxXuyZ9NwSVqn3yNduoIqCY2Yu/V0tdHNMNY7wWgONs6u31c5wSetydUo+8UjeHM5dfC65nMYT842SRXc7SPXparLFpQm/pDXdflC0aihYvvPnsNsvWb3BwtzGZroc0qlsTghqtEIZPXVPl2wtynXTO3K9tJR53Q10PSPJL/cBFr2LNajpfYQMWKkDF1rEdpcjBn9UUygsjkYkaprw21zWlEwZIiMz48wWrgdpheoIR3rJ4XL7Snz+fBseUkG4klmt5CjvNRTR0TqlomMCQYccmdWBfxY3yocUoMzExumvhs4kxU5v090eRkTU7d/Q0QXqccbKzlfSZq/cvLa2uVGl5+9Xx9PRK4qywQ2DEWvR3UXx1r8y2XR7VD9ktXW2/aHwVFbZCykL9YHskODCWCFExdPdJpwPZyjTMwE8znAPvQvZNGNY/E9WAJmrwo5OEmdc+0djRQjj8nD0WGG+hNQvPR0LAf8NzZBMyrt+6LOr91cocyYPb0IPuApwoCr2mCFYlKj0q1CJPvWAOwLNewN8aO9M39e51/cNDG32kwD9ZfDlZ0G+4Gb2aDoQNGbD7agWjFiqarEySvwNF+XKH93QPGLRAcGTnGdzMAbZcUx5Q7dP9KzV13MccwJFHw24E4Lsi9kRSScSugp6DxEI5B1kYzdDe/eR09P6wGdWGn25rct90zc//tCjO9ZZVkTXkwZWJrls8hhQAX/GBVDHUTFltokbXQg58XuRyp2+tLR+noE0z8uqHzndMxhWQbh2HKbSultSuSsjaAnYgaRGOc/JQIaVwNsiQhfNuIekQv9vaDzmcdFEs1lKPtZILqaoMn9LKqCBBHxhWp0R+WGUlhaokQ8bL5CN7XnaZU=
  template:
    metadata:
      name: rclone-secret
      namespace: changedetection
    type: Opaque
