---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: changedetection
spec:
  encryptedData:
    RESTIC_PASSWORD: AgCg9RXYliPe7SfyYnGknjEoCHzMgeXtlflQckZ1aieooitARwUkrf6/TH2O7I/Xk6wiREnD0tzJ12/1H5A11d4ihZ42K55euklBYkN5zPSPJgNnZCDJYEcMjqosNAsBgYHP1i5ihtRJ18H76vO8IjtMhKAe2kaMYbx+/aAAVH1Q3reBNyG2wSengClcTe7MHLM8CXc2KVN3DLEBFp77euAE0KAv4hE9KtnK6IxJEMDrhTykEjD4yBFybV2+/3Gq8baOaEn5dzt9RzOLteKjUKfTHpWgqnd87KfpDoHjSaEQk3duAsoph96LaCe9i4E+5GdyzjX+JZEQVE+a84HNQ9yMFdoiCtsEW6e+Y7xuDlDaqnX8oa7+g0fcaLoaYVRZnkgaaYd5aAls8n7EOFRLAwd8jRcygOh4xt3aif4LpZrTAJIwHPP9fwYKYsFSeV4yFadODKTl5SR88WGeE+u3CmLmopuSt9SyIZ7V/polYftwsdtY4synKhen6mK4ZVCMe/tF2fMdrKI7vWhzayTZ2Apy0thaEf0hssjHsuatv6F7IKdGekplyNWOvqkPpQbZ5E2/BuXMxj0prUXC65MJwV1fWWJ14qFLuauYTK/30mMxL/HTdY9BBOLw0kuo0oR1nEFffjg+QzgNF48SSf1gzdYbHyNajcbNGDh48TTZG43mkJ6gEOsyfQWxHXotw04PqzMPWA59lFWLAOomJ/ZaBnXkzuzD8mi1puLhsxMEPx3gQ+g=
    RESTIC_REPOSITORY: AgA5iSgiWmMdEFtJAp1ABfYOLaKdWlxv5RZ3s1dYr/cXf9dGA4IA+1NIhVZULl6ImHtAP3HuC/yqXNzvr7xdEynuseYWroQt0JyM+tgQuCrXvVRGJnlkqwwT2x5aHXomX5ELw7Nkm3EFduWUASGToGemtJM9iJ07ehcBI5hj72feXhuXRMYBf244zbSoAODTMXA80hHNnYVTVY2LtFeyvcjba6RFwyIroScwbFkn+L+7ZiZ+WAJXMI8M0ZbIdjddi3RDgLay7fggDqMiSdp/aTx7URaZXIZgYliqPt790exCCm6Aacmqfgjk7xiyNlrdYg9GV1WqHgYYlCXoyuzIuxZGKSUfm/LHtaeJBpcLbUllpxElNO1SiPKon+0/ddKEkIoKks30rTIY128a2vcszI4ZmH7zG+a3924TmDPz65wiBk3qy5bMLhXg0MYy4eozMOx+blhSQMU4yqM2alY4Pssbywnwt9ATqofk0ydjrS7CgNEMlxoXAV8PN5a32IdIrKEq2k/avX1At/7uwJqnUT5pBjHwDs/gCaB5J2MWBUjo3Sc1PizgY8CKnAY7HnLdPokYjXcfqw4iZuDGdKtHItRxOf4X3WdkKX2nmMNH9bCUoPbKATYcM9Bl84+uHiLEHGvDQIdRKZEPHlkKsgu7mSBCA40wKN2wk3ITSQaeWqruXqfEqUdvsMMnaetd8KMIWUr5+SUL4zdE3PgWkvHqneLDbFv3oMpKMvjugS1+hC8hGLt+LMBT+FdujWI/
  template:
    metadata:
      name: restic-secret
      namespace: changedetection
    type: Opaque
