---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: kube-system
spec:
  encryptedData:
    RESTIC_PASSWORD: AgA+7tVQ1o/xheyAAu/18zIqu+oEmlwJ8+KfiATSELX97hwejh/R2+TtpmLYgSYHQy+lLf4HSM6XH39+ie3r5+gLdB2O2Eq5ht4/bDn2ABX37oqu0VytQ6sCX9LW0k6kf8E/2U2mK93F++Ac9pAFCpK3rRWJcn97CxA2vRZF+atwmcxOPKn4T41bF3i4T7Hzv23ns0qImm+3kuwN99NEuL8N+tyLxSKePlW/fqFEM23Qd/VTcT+MDEgpaLO34A09OTg49YoNhf/hLm4qzizeh4Rd5Uj7Yn/riEJtDrl62rTfDkjvy28RkE+B8FOYkwu0aE12VdKAwv23qUcp3AzZrAw6JRhBrYli2MRxiKeA5r1D6YHTng1HNO/eaIph9irOoR2w/5aZ2ggp1l8aGQwEL0qYPXVwoYZI0GYbo8vn4lFbGRbJq8TvbE3mNinCYV0l9l2bWB9tm3cZ1+t35ufy8nhPLRj6VDU2MBF8hU/soFMvQzZ3U1JEb0FP3OmsdZJu6DoRri32uUTiWlf1S0kkA4aTsX3Eejshv7qdhn7fTUdi7efCZg4QchetCvCoITEibzu+ozcfBwEbmQF+2SPaKmP2/KQTwbcmWu4veIIyThBIYuAoseLon4zt+p2SUlANRqNwX6Ybsfn4TNR4/h2DPhuv/EQxXL0HcGkv5zPW9k+g4n7kTdnLvTWIs9lx/c5ObIY4T0gM+VwqqMc=
    RESTIC_REPOSITORY: AgAsYQzQmXmGf5JXShLSNt8lPos7ZmjaAvP8u6qW1joBS5+KHqnkVbHskNnVDr3EIyr14hUvPpAQNu59G17jh6+LYC0yHv0n8CBwD1zXUcP7baMKR3pwXYeK4F2SV/2It/NVdoX+CG3cHH6r80eURI+WaMSMfxGtpZsYtkkdB/ttejXlvvxhOrklUnWiSsoij/dmAVrvrwrYzq7C5Nr2RBH1tWqMGMTtzifbfL2mzP4jxa1uJJS5yBBVnT2pfuTYTwin3xi21qK98zGc9zxTRfsmGOG04QCGn6rBkRiFxMKJf4Z0PF2pSXN0Gd99ibim0jwgtKjwdJGtlTRnkSz3bhUzCoh3qtTera+FmnU11K1glz5N7r13cQcowon1vpvzY6kC140ppf23iT0mSiI/OTi6js5/85MTEb8f64wHkKqAAzgs030MniDruRMVLQFK5Q4KgfnqIHGtFzPbCDorFQiOt0vQIWydB8Kn1/oUVM50ur5X33W3vwFuGhiPBNLS9X2WAXPgEhXGjgSxhMZz0SNyhZtA36ps3knwXUFtHqlK4cqazpaWIIJD4SFtJ4j1+yiAR7mGsucFr5kBhuLxSmwYzzjs6/2Ij+eaY6VF+Ki4a/G2GXWAmKEfAPSAWqm3Mpigyk2rxsVra9X2qrwyEErUNjlIgRvwl82Qo62NMKbWvyR2SncLISQIx4Y1dQNamORuddYxQs+B/f793WRIctAD+gONavOa5/Gf7DVUyiYHUbAln0BMP1FBOw==
  template:
    metadata:
      name: restic-secret
      namespace: kube-system
    type: Opaque
