---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: media
spec:
  encryptedData:
    RESTIC_PASSWORD: AgAkGD2/V/3ZqAU8MiNtDjHW2p2DA/XFdZELsnW7B0VexSNKiNru02Gb7sKJtW/EZhbrdPfPhfmmdERCEcQ1A77f/WYstC9NXqJEpbMDEYtS3DFaHIYSRv5qGxi1JDPyNm9FlLON6cR5L9HbQhAS2l5FNFqsp3pcVOw6K3U6/J32lIrW3RnU2+a5PQqh9/NxLgylFccXZmOi7rk9T11rxr9pNAM4Sijwtn7Lza243dCfGAcRYZGFoktTGDFyTNu5VWf5aXs8Kq6qpuYIPwYMRIFSDcgHO8j7Qo1xT30sZPThjM6AL5K8zSc0gidMnA7e4zsvsliBGJM6/JxW5oqRFklUlYsYzgTSsUsLimXsv4TCjNiZa7fnFm7VH0saXq/I44SPzi5Vz5395vCIe5wIiiBs6ozei7aegrb5xsNIUaNGAcE0Brw6klUphUIJuYHtHJ77X/MfofXmTjwvv5MQYYD5c/dvpielRcqYjalMzHGke/K6kFfYq7gaquknBubqjObmi++J4UMbfrl405l34OSS/9AjS+CWSqnsYwkRI8ieOOKs79tcT+rHuaJjf3PFNOGpG5OEZuUZZEO1LaYjt2XoDY2k7NYG1JyNMfuU4vZic0s+oAZwA5mEm32GPgdmI1AUtgF/rP8ndaeO1zxfHPAxTheKJAlpJlNYdp//59SNoAz1Nb9mFN8McRl7eBG8qsToq/CuitQBFlNhJDeMZ+FPjYUZ6A3QeR4nb0Fi1NsWaAZ2lexwrDZo
    RESTIC_REPOSITORY: AgBblTorZLwik5VF4fJ/R2KWT3P2/t9+mKbDbJHTTi7gopIxeo4P12MS/m8dIbyYIRCuztImdjjytuYv40UB7dHVg6218Fjc87YmrFJocdG/WsVpRoaEe22moAy6MmrGKC258mfaQvC1n6LQrCJD2pg/mAcsweKYYz3PcBpYVPu3FJAoNAXqLUlU8Gc0XG+qq5ZrBt8RXf6qJOxAhHElysGkj2g+xIeUTpJybuj4hXfbpZBOIMSGgohCsY4tmO8yoYuWsLjw04D+W5O2Yw+aeAqADBe57i7tJUETW6C5ptjk52AQLMXBTf+51YJjtEnKt3r0ofmdnyk0ztMxZ+Rte4b4u1O28BlL5oSgu9EuF7JlHUUx85xTFb5cFNT34am1zijRus/5czSHnRtziFTOpuurKNRODmsYJhLcZ+JnC0BhLbQa0HbjH+vUxiU7T331wlBbXgcYaiYK3MsE4mk1zBJl1rofJbOce4JgqU65xBH50hSNMaqJL5boMET8iwMVmgySJ1kRAINcsm46oDxMqpCP9GwEh3xQgmWt/owgdK6hEuGjbiXnhM2TqRDQAok0KrSL0KFqT/iQxGhDv3L9YrA8xAwbHl6khCncnY0NB2iYjFZlfMKU54N3CnxcRIId436xx0WzwUJLIS+cWdbc0y1rbMZt9Zu3ILdUK2jQCN//znjm66xnRVv4suZ5KZUz+lRJxnVmS8Mo4pDEg5NHvuPm9ApQruzvJ7+C1Yh//r5ugtbMtaDE
  template:
    metadata:
      name: restic-secret
      namespace: media
    type: Opaque
