---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yml
  - ./cilium.yml
  - ./cloudnative-pg.yml
  # - ./coredns.yml
  - ./democratic-csi.yml
  - ./external-dns.yml
  - ./jetstack.yml
  # - ./metrics-server.yml
  # - ./netdata.yml
  - ./openebs.yml
  # - ./postfinance.yml
  - ./prometheus-community.yml
  - ./sealed-secrets.yml
  - ./spegel.yml
  - ./stakater.yml
  # - ./external-dns.yml
  # - ./ingress-nginx.yml
  # - ./k8s-gateway.yml
  - ./gitea-charts.yml
  - ./jameswynn.yml
  - ./zitadel.yml
  - ./aquasecurity.yml
  - ./reflector.yml
  - ./descheduler.yml
  - ./fairwinds.yml
  - ./falcosecurity.yml
  - ./k8s-cleaner.yml
  - ./victoria-metrics.yml
  # - ./kubernetes-dashboard.yml
  # - ./twin.yml
