---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-role-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgAp6NIrn90ZAmLsADdIWZ/jbg/xgBhKoa+0KTKAyzM0T+wNRSgxOVUjOMHb5nT+AqsgJ/TY2OdlIAGc1605JtNRA7BDkx5OAEUzzb+M3fz3iYh+M4shsDjq9XtZraMhesL+XcmaNDyfhVt51+NDSm6eTrZjSBITKSlpYHSOtMyRDqN+NgkzeSW/Y6iWwtDNI2u4q1H9erLHi/KemCHf94Rg0mAv9NYZsFpqm814dIdG4PnoL3CgMDXRNHfRK6a+uvR7q5bIWy6Ao9CzS3QTDDKmhVDv8s9is+ioTOv9OsaswnwrOktpI+3v1YtYxtgHTYxqZg9qxb1u5MJ9Zf3VMjB14Mw/BCiTAAfSosisYDaF8c2d0oBs15LzzH/sd6tB+3Btr3rFrK8IAWfVTN4rUZAlugj0EEq9xUXM+dm8D6MuYmvE7SrcYsJgUQG6Q7+J2vy1IP3ppi4TFFKirNlrIVtA7jaQTHMb/tHX8yw1QvXyqIW1ksFIDdzHV+yEcBqm9FPMhHTtFP5sFbYIj/BmBDS2O3SueD+mYzH72fBsaI2slGU8ZkKpMMQC5mrPsOU9bk3Ao6/k8vKtU46s3URlcz1cNqFAIvtIQdWvx+cCxINZxPDogY+DuJh7fpcmVOrajiux7FUapFqHQrtSYI8S7X0VLc7Xwq9cUajpgkFbpnC2tUGFeZuCDXYpFgLdysh+KPxNf0kjOeYKrFrjzM493ieLd9EFq1bgLg==
    username: AgArjj5xRt/UV0HlH5DpjVoTZMQ+qobN+mb7glkjiTOJwPRalm4+aT60nrMkNHp5V2k3GZciutNUVyARTa8ayB32H2Tl5HsIlqppCUzuSh/EjOOxui5rKWJxCCK1GI9yVv3ZIV62bUmkFUjTZXAUdGSZIxgCNPqOCCadodd2Zk3nKyEeTBYn2NR27+T5OkUrgFX9TuWH9kwTmB6ZCIcznzQEM9OIZ4JvucsN59hWYto1QOG0X5HwbwcXQj/O6nqxYvzE3pRCRDrA6Oi0TMqCBU5+h7pw8/atN44ObvjPaXUFeVWhQ+ksdHLlUcPzgL87c0c7HS/63t0RPxMaGPaQ3aqyCtP6YOgVLl1ZOSH7o42Fm4//dQyRyEJyYgD4Wc/YALFRqvhOxduPsVi7G1orSRoJSzOcgZwgD8tetDCNfhCpgUs3HNKig/SA+Gc/1MI2SXuZiAPQU+zFsTOYozb9b+KAiQjtX7z6rN7IaOHsOTD6TGAr3JYJj/08002K91lGcvpAjLtQbP5P/nFSM1C6UGPIwHQZoLJaLpTvK3vlrLCdIVcmfQ/X6WD/yj1T3P8gokUqNpJ6d4mZdMkqW5ciqCJqqlt65jiJsQSj7CiiuyPNbGEkz8XjeVUA/VqS7wJxgQ0JACKAeE00NWzRm2SdzX1+GLByFi40st3iPtJoStSq8z+a1cj1/7SFbqq2mdrgIlhh1mOax8k=
  template:
    metadata:
      name: radarr-role-secret
      namespace: postgres
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "media"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "media"
    type: kubernetes.io/basic-auth
