---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-pg-user
  namespace: postgres
spec:
  encryptedData:
    password: AgAKAhwPhN1iclHxyHhDclW0xXImViKxjSH7HUliy+SKJotsTlf/J7vOi3Ln/kFS4Y0ea1aKxId3QhUqvRownE6h86g3y2x1z0MgaXieNf00R5s2IZD/JD9yVqv3EN/1z+AUmoX6vgQ6QcppfPiwPm8OejjvCw4lpCoTHyrMpgcHaiOJasptaC5yE2g8F+Bb0b888WQUQjP0TIOct4z8foDQgmQHvXuDtB8gJ6N0gW5iubYLU0UFhWEm0YLovUXZ/pA3eRxB3mZIUtq+0GILKJcgU+uRACuTgo31WkFoIEowO4LYcpgQd+pmkzLVsHeZhYaV1EUXmowpV2MCCcSVe6Sv9mkZ6vUGBgUtBz6pTmTdzH8FbsV1/HvS/FKUSbXCUs2W5T/Xtzbm7IIqtlKqWfZavOMpPZB9rfyGlrF+gMVWuz8rCok2CsbeKh/ysn3wTqQ67u+fi8JARFbwrR0lB+R4+sVdzZz0Fvu94G1pxhXu3qnJwLYBSOZlKc5ZZrgtIHX7vvMvfQPWUY1NNeZ+xuHtC42s/Wpzn1XElxnWTWbGxcl1gbSx11VOE46oNs/Mh/M13qwbM5VNsy/7exSww/IzIIbt8rGSrpVnDI9SyMkGAEe2qdlewRLhhfIcic3qMpWUurvLtgOsU++/w52pmARvXzCQYxPPuRyyZY3mmYZ7fwSXvlBuyw94R6VYMmzPSOT8AmHDInlti/A3s8MqCKlYhJtDHtrDiEtvsiO2A8n0
    username: AgBN+naM/9YODL/BBFtq2WsI7UYEGw+D1YfDdOKa558fMIZVDa0JKkBNZKf4ZRrmsj35sq8hhtzM4t7gEypvd2tl3EC2JQpfGamSJradjITXYnami7VBGCSQoBrRWNRRxLiaMVV1MNGKdM+IIOk6asTWTAf5wlVSCoN1wd5LTGdNwHFuw/tES8aG+FRiV+DQxFRu1z5zWABtoIlRb112v3LMh2ysfIglArl3K41kJpqpBcNezwASFS4G6Cd3Gn1VpPc4VI5+wUTENA1Es5sdPuDopYTSZONyfr/bjPolNJk+sYUuNfmaXlHaxvurs1W+jvgM4WBLtkuPaIOQI3hEk7o3CFazdxgYs88Sc2+1eQhQart4/Fre1x+qn7wMmtvzu8jCbZGLvU84ztmdBNiptKAPAcSgdqrcySwAzA3r5n6y4Scjizif9BIWGoIg7uvUZAs6sY6/lraHy0u5b0D3jyqqSCh4puh4VjuFQpmSCAGuMch/PIGTpzb1+zy6hRn9twUVfkmayABElbpkMQYG+L2WCPDCdfrDiEUbxqR3daUmoYPLoMQGvBd4ZdutAojA4JKG0Ka/RPD6AsgIL6O5gicSs4b2itxI16S/5cBBO/yRcRWBVSwhi2kTMQPszasjiDXqFx0J3HF7cabwQzH4l7fT6zMgc6DmJJ0CsDBuov9c08TDZhJJH0rdigL8xcJo/Pm4w3COWTQ=
  template:
    metadata:
      name: immich-pg-user
      namespace: postgres
