---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  interval: 30m
  chart:
    spec:
      chart: goldilocks
      version: "10.3.0"
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      flags:
        on-by-default: true
        exclude-namespaces: "kube-system,flux-system,kube-public,kube-node-lease,default,goldilocks"
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
    dashboard:
      replicaCount: 1
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
