---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-secret
  namespace: gitea
spec:
  encryptedData:
    rclone.conf: AgDFLq75QAPYhA291m6vVePuNaAw9AzOpA3IyWUYiFwLpdu4+2nHlAgKZPaKmYqtZgK9CZzeC5gdDHZW5AsExJQjH32iAN4Ui946h/+WcOwS3KcK+GVABqP/uba4d92t7DdFcFNUB+1YtqDQN+kqBFhb3Lz6ovpFB+eclVakTzqFAjl9TTnZeM8aKCQ+FG4lEyNZucxUH2DygF6xhyjWPq2VNea3C7UNUrqCqvw2KUkOX3POh7ILlNyrLNj4W+rr+JhyylE/yd0dirlqfJ6lFkC1+juEuzmNoThlokLAV3Tu6sY/ziCcUDAolvgL1unlYuDaD2t7WFK9FDMvjkGo5+JVHHOyMe9bZqr41lo5Z3ZR5cK4SDaGps9+qZ72xTdE5+28vYBuXKrahnC4UgkYr9AHFwNVovM1rJRQ7HnOl/bigJLSUvjZh6FiWhqQN9Fl7lR045OGg33AeUKqpSCrmTGC3LXTTa94QlcVLMs9aNz4j58zUt0jCJiimg+1Zi3gSRPdh2hnNUFKvpCCvUxjZwL/elZ4NamoacKWAlepExVXITgjQiRtYRIVxEYMvi7/fzO66bfLiuS9iJXBE6PIBNv/CA2Celmu8d9nXzZVJbPH6ejXoZdi/8cGRSaHeYOeAbWtQ7yMxoPAz33WlM/6kv7CPdSGhn5syDb3YwEyKRyfPuY7zSOlbVmXVaEJgUQsSwZn6b7pxYh2I+Tu4vK7tqRNf0TwH/daG/y3CknU01M0BSs2LyDJup2CsxFPNo54dzMPVBa7EzsBIO9GmWzocqCmZ/MGybz4gb8Eaz+oLgXRmULm0IzVf51e7Msl8b5a/XjavEv7U9Rge4K7HplpzHlppH8QjhLPzST/uY3B/j2l7mA97h6fSAOQZEi/Kt41Ky7t8R/aP6RJYcJLJinhEWd7q/F/noeZ9DXbx6gTWAsmyKGknY7+I0+FEId7diQh1RlK+Faj1dezHDP35ygRQC6u7Snj15SlHuEaCfnDuEfrMysGqf6AEhylxr2vQrLyPABH1wnfWGE0K6wChMNBOkGf1bE1fJ1zx9L5h9hiuO9GEICrpsof7gcXXyumKh/EZMxHaAGzfOG032W9hlJhCpQnBCx0worE07JLToreEXLu8YEC2v7a+wJ92ziqk9uH0bp9zsQB+88Ofzts7TwfXmbJcptTehyo270+apuTFK7oESXhDh+6DZFTeLLGfLr0MC8ZLfsu+75uSsOKrYbTbD4TTsBpvFn/4zY6bCxE2L2bAf85WB31Xl5X6yaKZ9As8LtfiQN1sRt+/GSTkgfCiwpPG/koOZ9o3sxsw6x69tHRVLwwnP0Dqphj+CwPaiQcagls+xFXLLKaN0jvZ64Aa7q3sFfDA5erEJBb7giCMn1EAaMRdgMMTYarJOy6CC5VMdCuDTR0WBw7BZjyQm0qLU1kKGGuMCLpnIqIoy87qZ9fTrmsQabrQDZ2YQ4KHeBnaTgGZtfpPxnz2O13mSnVUQKo3yuqGg9+CKylYGpapc2sfIvb4pUTfduxShQ=
  template:
    metadata:
      name: rclone-secret
      namespace: gitea
    type: Opaque
