---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mailrise-config
  namespace: auth
spec:
  encryptedData:
    mailrise.cfg: AgB086leNtuSdjXaybXM6RQLcHRpN+eC97Yj3jxgitV4xmjqobn6+bryNEahq4UX9fcQQg/dj1E0bEwCuMUdKSCgXNWUjcLm030faOFwhobDKafFwSL6x8N0OrZJOiYRfa0QFj2DTgA2REtsKaFQbvntTOXAlImegnTadpRHOR4i3YA917ZQR4gQvevelX8caAzaL7fxUDZfhFhTfWKZe7LSCSKmUMiV7n5pyoZ5PwtBmpLg1Ls9i5JrjHlAdulUsJvN14IDd+GZezJfpxuvtFT9d3+94AvKdgcw2Kjx6hMq86uTl1nlJN3vEUvtS3wAuSRZ/cnHeEQijf1XGLiOEFaCAVC8Pjw5+cu/3laKHmccMtxEKIH8sbDkXBDuB4WeLu2pzN1f4Xl6MB93ulb3WC4nDo0vmtvz5hT2KruNBi2wEBLdTuneBVUTCgEXKku9li9AEX+Jd0rmjpL6/BNCEkx9vxLIJZwCh/woqwZtgp8w79XoFvvGb+eqVLdH8YRpYVqp+jU/caEA9jQJoGIZ+k/70iwLq0heCp53MvRqWuGSc9JtUEc5SuKmV+6ZKBDzWIv3xImssRQd4hRGD1ACnAyFvsZwjZS/z9lupQZ4HRUw37sZRrAIvsWUZsUqTJQ7t0vOVPlKVwa5K6uekFmDA1BT1VyFvEOEQWNpQlAWtWm5FIE3tb/Nu2EWmmcdEEoRiE5SlL7ga7aTJXZIA8unqcw1orLJPSZDxfQhkibDlsGoguYyJnwX+J3grETQs9bbwx7zD1s6fKHypgsjTT9U6q1BJbTzbw/+lM6/tMmPut7Z2mv7I/JVmeSbEu9FEWq422idVs2uICcQqxLYHUvP4AQpszJ9Qaw=
  template:
    metadata:
      name: mailrise-config
      namespace: auth
    type: Opaque
