---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mailrise-config
  namespace: auth
spec:
  encryptedData:
    mailrise.cfg: AgCnmJ6X8jv++loPpP/YzchpabXdPUALPgW4pWxS+iXBfDx6vt59tPaf3D0lkH1yf88wJp+xi9fmzZdK84YADh0zFta2u0fThbwSmojYB30oujHRdqRO8fVND0IhF8YErkrNiMBBMXnegVfJuJuZU/5Y4LBGB4Zga65rNue/0fI7AQYwCqrUjn5w21xbRNrU5MpNW3LA4e1kvj6eSLlUxTGGbvhgg169h4nvAS9LKmts5OUFMMs8xLgUSIAtNpcy0DhXP39L/onxyvH2uAojwUGyk3wFIgzj3xENGco1kV9bG35NrSm2X15y3EbprOT7GuC6QATn92ChyD1xTNBNFN0KNAG0v1S/JYD/ZBdYlXOYAh1eeaVw985R6mX3+WKzSw0tFShnkuekkuQ3x+f+FePl+axUXNSMkX+UNFSK2m36eujCo1jip4diVLZ8qAPEKWqKca2ZeqvVYkK+4KJsNXBqaelrS8KMDMGAbn0SLWmT+aNTwabYjv1pHCV0t4vz54hePaMN4kJ9HGRKz/8WOJ9s1huZF3bOs3xjZ1+83u6LlV1sYaO5wnIRmoD9WR3OZCMs30LjORhqr4bzPiU0/7t3WA8uzLofQZZW9o+x+aj+fG89aj2/wMminr9CXYFn9i2ZkP4ZOLscMvwpQeqJyrRzBuiIKKZvbnHUyqIYw1vxuLy/yy7mqJ72x1S7YILQ2wTfujN9BgyJ/cb2BEgfvDGyyV//uiNvfLUfd2Uf0b/MPQpsl56Who3LrNB00kIv+MiVO+WC7qGXAIbiJNobiOMzSwDfpGwX3lsEkeIb7vJwlwG8eztp4JuVFB8mzuhcPs/Li2ZhzAZjESIq7/VzROJ5naDfR0Y06qtjP1N7eu19NmAiEnyf
  template:
    metadata:
      name: mailrise-config
      namespace: auth
    type: Opaque
