---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yml
  - ./database/ks.yml
  - ./operator/ks.yml
  - ./keycloak/ks.yml
  - ./realm/ks.yml
  - ./clients/ks.yml
