---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: joplin
spec:
  encryptedData:
    RESTIC_PASSWORD: AgBhNLVHSJE7hWmqO7xoSFvKJxt+XR9hGl6g55RxFu/KkUizK2GTgxESRppaglZB12NZ52XzqRjdqNss9WpMq0P9HM0smrn0XX7R7Hc176WlubX+YuloZO4G3ExnY38+8A+pSOJt9fXn/k0qOouyf902VUmES69L3Pbx7xeSpm+KBv7YsL+WSrROFzJL4xt1uzNZPw0GXHO2OsOCWpjnJODD9MeDINwx07eTEf8uzZoBAOxc8XGa6Q39Z9fJrjBxmKusoP9dK6k5YcWdoQ7gHsA6Q9B88rOdd7RlBe3nKu754F3I1YogVm1gY1UhMaP2/xgpr7GigGaBRRlqDuHftPHkoXJotIYtuhIgABnfXwS48WXHKPhIoGfNoL3cuqynDtlpurjeIgmliFFCS6k9NW4Ndqu1RqeuEaloe6TV44sciMbeflatcltWF0X3yEGU6sr4JkeUbHUt/CYULO+8+vwjBUvdiQOlugnIXhcPiC2noQhjJpaTSFoooD9ASF1LqjnbtxKqJlyCcAa6DkB3JRUK0PEMK4NPMaF4yuz4XqxDYoTPAKoCWIVDsGkiUVTek4JBePpH4Dh6iBcVRBOBQoKurz7Bdp35FAxG4AcnEEJCruvuGnDTV/7V7bVTDuqSJbjcMLld41lrZ12TLP5Yeg+Vq0jpLkSUZhh/jYPhaneSsNMC0o34S2t/1xx2zmrb0ZpgbOTv6v6rVLTgtFmKlZHkJjTthmvotgpjwj2SABr22uI=
    RESTIC_REPOSITORY: AgC4HRqpwA2c0PJvv/PaNacPbHIzJQXs0oWtxYTXXHFBF3KRETq7kqC1TgglOiMaVir85NvpMB7KL8aeMrU78jfBp02grASEWI8JrelE6In0skIrWXTr5+7mLt5eOvoiz0Ht8mVtCjJqM3BJY0SG6QjZefwhH2tOM357oL2RZpmIibAdpLep/KpSHkqPo5AiSyw1lyClzn/z0pa7rSeKPkbxomSpJ8rxFHjat+vtEWmBOvJpKhg4Dyd/Dn/djroM9BNEtDnlSDdYI5kflL/CL/7x2CRQQTS7tq31ACe/9N0Zf1eFOTcntpdzWPufQg+PlUFeXULaMpgpmf+V41zKND9/ldIz6f7h+HiECDOrMl/3kMJzEn4l++q0e0ycQnXLcGCDhQhdUcv14cymuI2PhBkuiJGYoWr9a6/9mz8yEbc8FZ+flFfsH8saq0XmH7f9aua+/w6xGe2/WQbgFHSQwAcS9uJK3ZZXggrpWoFFFBM9RZPkc6JWKAuSldnYswggr7BOItvMzcoSkru2Cy0H4GtBidvK4el0miVbJwAUq7pi2tltt+BZOui6eqYwhZWINRnhKd+wem0Rbr0EbkFctvFAhhXV6Hsyw7SWYGTVx+s+72Tt8CkWPKTUFxnAAZhXc/lS9DgcCzmJKMpFYvBis9yAu1pLrGwI8d9y65d6nT32zll+GGDIxU+EamQ3hIP8UjZhPlGq2bQG/jMTWU7KioOIZ0o85T4oURjcKNUhXcR69FSc
  template:
    metadata:
      name: restic-secret
      namespace: joplin
    type: Opaque
