---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: litellm-secret
  namespace: ai
spec:
  encryptedData:
    LITELLM_MASTER_KEY: AgBGgyNhmTY/jBkFz20XnbUi+0VqN50RP3J83B+ffDpGqxLeyQjAjuWvHElo2C5pGCQZ1qTtF5fqcXkJd37NB5FzwKlfUeDHDZnQi4ZWgy2e5CFIA/7z870waZZNoA08/YA/sdtXZiZNazjroTzpqQk83KDsS7/8qbnYAyyd4Nwh6f7cXTA1i0nOvLkn8PITZS2ZOSOiUP0T2ZrOVfHqC5FI/4et7k0oBPjHxKAyWUG56VOqVyXoPLgb0TT/flE9qauI3kMAReHjzKH8Cqdp3wts6AoXjBp7yneQTv9D2a5hf7pMQ7ZQuFXRrn3UOBRo2n3XoOKyBbwbrh1vkwhhI52Z9ar1pVPGWbEn9kIl/8Mb2uNB9EmmhD8QVN9sLXMByE79si9t8R5C2ms1Y6OAVRXZIHDbS89L/l3MeGsuLS2EC4dwZjnq9CZm0elBJraUZlCLS5/Od18ma19kQi2nEc4y9ZipFmG7x4U9bJSPCN/njlyyiaxSdNunfzwAC8IO5PVxMd6iZutiMw06NIeOzUORNX4tkW8+2vM4P7dZY31pTOTX/Sa2Hetf/t8jvrmt66apqEKCOCTw40Q2g50ciVOc7KBRvZVwYFH9m0xa+8hkkR+un9Slc6iSQs79ZOX2+Muag6NFgVBHf3xuD9qLIhix/kL2+2mFqyd0GdNH4xVChF/Jwh9kHhNygREBmqSYdOe3o6ftE/PAwFWevfjgj06nlUQXYsYc3WPfbYA77V3137Ab3XLjBuuIYGcy
    LITELLM_SALT_KEY: AgDMMcDc3H5KTo++3bTl4g0wri8FFhw6HeB0s9rHDMWOI2ETX7ttMCwKY7x/ZdN8CJldn5ij5rYSZ4illKP1SpZIja5jP3pHakpvrNGUttLeCLp6G+rvkuOZX/qiIO4fdHDirH6jzt/WYYD+dLciLq1iC/xhlWYtKJ4gp2g+mev2Y1k/mPwHLL4lo4BqzKRIyvMm4VT0p9ebhFabMR2MnCZlGGBPwGZ4BNJKcCvLvIdUYa/9PwWegshYcUcGSqhwAsri7xhdS+gw3yi0l7MceWCmNZ6SDOHPJZCLZs5UX3WUVkhFDs2INB0FIkqXYAk46qOtJzW8XuvIg8nPDFMp50KPb2LQ27tlQh9l/8kznsm2xz3B59HwF7S2ioLcK7KQPPQDsJXn6uwdxW58hLdOsKYIER9qbfprZIO3z9RwfqKcw83QvketdVR8uxJxh+A4oZVRmOzbtmf263qwQaWiekkTF9/+JTw2CCz70s2BHXAEyJPaSpc2Si/DfJIloL3XtyE2kabvgmoneaNSUQN4aTK9FvKIy+xBN4gfKEGU9VyyfnGxOnsGFJQblssX+DgmD39DRdN/p6yT2J02GOs5FCCKzGh0D8pdaNDktD4RL01rQ+AUEiSt/+o0iHctGKeJJZBaMB0wH2+kY+O9j9kauOtw03NRhLAhCcWXosjYkZj4CGFjtMxaPXn4gBQ9L0glMfG/7AbbyEOaraNJ4PtSx1W0tAsZgl6II3DtWxg1LSHfl17wdjQlmSRjnmCu
  template:
    metadata:
      name: litellm-secret
      namespace: ai
    type: Opaque
