---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: homebox
spec:
  encryptedData:
    RESTIC_PASSWORD: AgAHsRwc4WwhWrKB5KI76yAznh82VB18qwoZ7pfLHAzW6i+x5uqYHIa5DvGy58q5RXqpvRXgX7OOANC5U4dUK5amqoU1nZkYmuOiAmgdvxNcvSR8yJey5v/VD6S1MezIQiOgXbXrgyF2xuCv1yqEDAe7jNhIyJWmTkfJcDPT/KTNtNpZO5I/+RUrQi9SA6OyHK468wyTxaivu/wS4QZJuu2CFhAKis782snNDy+udGq7xt6r7as58ykcNNIANGgeXbSTs+EjASu5ni7pKe1iQHnbtEc3S4TRhRNBCEyDsBs9PeaUKfU0jvNkx9rDk6tXfAH/Rg8X1S9/sQ9ugEPfleLm10kTfbInDwLTqyEJVCqvPPO1hi2NH1V9x9dblRz1ZX9ZbQakxhBpCfHkUmw0pBsv4by5S9BSdDMEA7elHYLqvKOjIFEd1fDxUG4rn/eeJrTxhbpF7Dcqn05vU7YcYO28zRfNTae2FcjFB9vSMGE8DfTa2FUO/pem+OtuMy4Kj1I2ExDZmHfXbuWUdBoMbbazLX95HygqYc7wSd1f6Q+6hBB122I5wounTaXmDeoFnslco6AGV/761RYjy05cyz7hmdkrv5CGEnM0l516hvD8zhysj9r46+uInxrQfwD09tXiHFXl6d6KK2D9rLt6a0GWdAhP2SC1/eM1IP6L7k251O5RqantmlYhjlliGyDUVfmMgBarMSHpq65gBFgfDxLNiZNd9WHwIJwDuxwnnEbsD3GYCaVMf+Qgp0rjPg==
    RESTIC_REPOSITORY: AgCTUjPcyVJ+84xHJfxUAPeVxjxExI9GzrUXnrB6LXeR1XuLhdZcu3InjAXSEjQsEHGbOiPbYv22yLRx0dZZVZ4Vkpc/Bm5nkuksTyPX38nI+K4ZVn/8mNvQyLEIvwBMgT6cjRR351ctAxAUbZlnPtczZ3YN5FGBjru3270ixTlNxypALbcMsCH5NBvpUklJGyHI7nCe2bGFU0N6QZjXlZ4C9/y+N7XPW6gti2WoDXCrDLbn1xEFwJXXyh9vU2Ply+YX4XNjY6ZdkC5ed+4vg699+woC2dQ3nuMfCdPahxB8iQiLXU2/t656RE5oII9tO1322MYedDciqcah2DiJeMwjteRgI4E2gDs8QID3MKieAohFW/5XwHFT0Vx6qvwk1a02v7CyouY2EroSk4zXv++DBjbyNSm2pnpYLATyf8G/MRr43+4yALFOva98NlPy/2DgfriMvaxLXzIjPrR5se8lNmwZ9VhmLR2c2EGBYA99EbHFCXxD1y4VFHfw8al+kmZCvGnuTE4sWHvd6TXe69IikQapInWFpNDxc5TL2pJ+B+3v58lKKrG7E0/lVcSAW/s1iOGDMJr4vxReXkpyz3ojkcZ6rzJ5L5d6d3yfmqcFD1xS00YFq6lzoR1GAwO3RzrapvDDPodkLq/nEijjxkYyPj5TYWFpz5q918UDd4HxKt+nuE6nrO1UVOpwMfiCpd4OVoH01qfr963ir3UoSmYjelF3SvlJY7BUg6XoxrOtKPddLQ==
  template:
    metadata:
      name: restic-secret
      namespace: homebox
    type: Opaque
