---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-role-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgAUeKs84uVQ35Fl0zTr2y6D8G8YBMgngSlGRIjhuVQp9Js9lFZfyKV7eKqHEXVQBF9rZRfZ0+2s1Q7GHKn8vftWPy4aWEj3+reQBLevHzmRUt9U16vNqFEQ1vCh2Tl5wdgSI5h0O4bf0RItPBeTdpzlWgzAte8n0RM5dVqvlbePgZzu/u6GCWruVPad+rlTF2Tu3EJDQ4jjXQR0m8XnlQRdZCcp1Bt0WH/PEVEFRamQQ5EiZPc7Af6EnmDIWXs4CVszfq3xa0N8WDiQ23xQ/Cu5FA8/1jkuuIHaMFArsdWDauGUIjxZa3QEEuWkHnBnW4fEP1cvR2tAsT0iS/pzJxvQrO+MlSSH7ciThugJ9ij3QdPISyt0Dhz+COHdMk9A6TH3hSwF1SzJqMRtIsGBSN8K7TAPfg+Ec5uVMNqdfD5tV37+pRn5poY4neeWqf0zFDmSZpaX1qCuWpzsXVZdfQWYQeouNKCVOTLz/utQB9E6BwhRlm/R8FJxlJUhmIa2uUSs9yF1T1Py1xUbSsu/4T/3JsKL4ZX4LrW0fNNs6/YhRwuRB3w6kDOYQroBQtHtqzXNXtedOVuqkF07QxfATmQeYQ9IHyP9XFHRHav/IB2DA/aIcpFTNj93gjrE9etv9UyzJ8zdrdK0xQhLtosQE3RA9Z+s6hyZh08DCQAHxxeWWMd4xqolgyhcDKXmZ+HYqGmeM5Uh6hDRW8mqHfTg4nfcdksHarLx4AG/pOmNz310rqycmBES/PdvD8JtnttE914RwIQfJrI2/ufGFmRWHWujWV2/3F2wRPXyPqa/WveRMHMlroJDHX0a
    username: AgAdGdPFYHaRu9mJAJ7VepcZLWeBkjyzVfxO8Kw+AMN51DOEEWoEI2ONBcXPSY8WqjPdgM0GbQsVIkCCZiKrLEbHjmTjswiKqvxGRgFCIqdhUqxb9zy8gfHvSJ4Z1AIX7uXdQ2Mt96uFbOXEOgWkJGvsGQUSJCVoZ8rk65FpYPSCl3P1OR6Xdixo1NAjqBxGQ6bwo9Ifgc4ACm2Nj4Ye3SVWrSymTg22Uz2aMSR1GEqxNbbArm3KaiZyJ9VwKiUlbJUA7is4ud1nqd8lw27GB3FFuGQhlJ/eitGzFYcCM4aO0RNavTIqL9XEK16wP33lwQEW3wqMc7JEfZ/0VIgi5hsCVrQla11GBBRoNUURbdsa4LtcFCMus3G2LFxDIK5SjygiXu/xJW//UraLOYY+F3CdiVAP/8DXrZAqFH8gEPLHFGnhetSPbcjpJwKWnQqjTplm8czd2G2U3u6KcfCPtNXFWuszKIdM/jeoG6/e1zLVJirSneBhgiY/PfGZKpc9+VIVNKGKrmn8NOnVA2NEJ579eOUZ2204TTnx8Qu2S+XkPI0gOEGhUdiEAMFdJ/fNx6a5tbTd3dtO+9e6oXqrDQjInUtGD4XBtm2OjUZM68lnFXJv9saZZE8aXTbU7YUZA06gxZYoakH8aNNuMxfvsjVOENrce+OBXhMcBFcy8JNHhIzp5GNXmUXnibu1e4oaJ5AnV7puS3o=
  template:
    metadata:
      name: immich-role-secret
      namespace: postgres
    type: kubernetes.io/basic-auth
