---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-role-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgAtPGmtHPCHfPlCwIDZS8vAbNmuLNDCkqeEa5jN7CPy0xCagTa9dLoUvx2kuAvJeVzOTSDHH1Moa1PZZLxLXmZx7YutAIgtrw6o8dSKjzhQGmMwYYOVouJZFFL9DxiA+bHtD6QAaw5BZDyeJ6ohTdpBrjPTIbqCjvNJ/OwUun8uHmAauDhbbSNCpVPRQXOngwjYYVp4kyKWfx1HfKW6k2bYKGQf6TPzR+SCxPNAuLyDGG4eQVtBGslsLJXA+m9aXcndReaJo2ctGyDn+sOMxrpuuh/DuhAPAXpzvHiFJ4Fb2RBpNv1hZCWZJJiiLzklNiE2ZpN7ShXz4qBW6MsZoseNUVR2EG2Glg56vL5TS5xIa1Oy0P1dVI/fL9u4kVnUbxE34SfvNYtPlB4obibLc5MoTOHl+4ZJLUdEbf0q7/dApHt2Y/z5zy3iZFfJRu8EarPC5Jr43K80pPM8MZS0V2EjdNi0pi7c7ITMY1gjMqYlIWXwi3pgNB3H00Wjcj3F2A5cKquar6TBRxCcsKeCo1FmnyMtQKceAdfoUuSlDeGvgA3fURH+XvUI7GVxOzwxE9r6UMjQqy/1I0ysBmc4yayFd41Ejds2/c2jXfcFbp2o+FY7AZDyyB4t6VWJeIS4E9GsQAQoPbF1liRyuMf9I67+jsvNAf3H1T/HZeNy1Pl4NcqBf1v1dIr2MWXItS9NOagYIG7fnrrsx8MPAoA0i9MsTutqtU2ZaQ1Nakj+XJkMSLtuExsdI8G615HeX0caxjPL3TPsF7VGW2GRNeYnf9Oz
    username: AgCDeptTHuu1MZlvXiQc3M0PbJ5E6usPzV+dcMIb64tYR0+ERhtsZbIxcJnq/xrMkXyUmfuPU82XmdU29x7FEmjtlna4Y5qe3zlI5mODNiNOdFErPNHhK+uYNagk5q6wIDAN17U+i8GSBuI82zVgZOGxie/mpAGF8jzGHb0ePj+6D2nSDowSrWhHPiCzT5kamc2JSc/UIl8ySAPrngIz7f7m5Z+WrLHfxIuDx3luvpt6Yye3e5e7TfNU2RKnug/0JlfizyZJK3lrli+zWCdO8tQs4133FNqBme6LXWuoQnzpAmK0RHTCV/bxCLoxiH4CTMyuvIQ4lqqGxAeN+njlngG6f88H40JKnw7e+VC33zIq3W+wry8j/R5zXKNbMIrhQUGp2mMmZJWM1w2X9o//U/VcuBCvv+SFN6D2Zul9vVaCecH9m4018HCwlJx58nRVEy/Sv73Ut457+zfR9dJX9hbvrrTZlKgpg5LWrG338hrHBQatT7x2JuCMPivCilztAhyFjXRs4PpAnjV214CfzIxOfupwTX0fpnjqHg5+6GDAbem64R+s2fcNYaNgBzjAwNNDZj8b7AMNnT0dOlXY8m2dboeW2xluscl4r4MzZ7t7IiQzrmNDeAF1LB79uCzJ2VXn5L+yP0KmtMX+Df+FL8CsSbqea9U+Z64fFCXwCQYOvw4fU5xZvXML6xzCQFSVtv7FXO16njg=
  template:
    metadata:
      name: immich-role-secret
      namespace: postgres
    type: kubernetes.io/basic-auth
