---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-role-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgCfiIb4Eqakm4aP4Ykwk2Fo8PkSXN/FewVpsGQ/Ko1EoMvUBA5EWZ5/EEFPHPe6v/1ZRi0wYxSVgknWDe3TNBex6lIWbdTT+NlBaWViPRh+OianEQwfHI/Q8H/HFzlPE+nPfw3nl9Ps0FmA/F8cxRLLsbOysQ3J896NCJXVmTjn9osMMkI1oJ9+9+48S8+bCKglkAcTDhz60pKnPs+AM+ZLlupr+6ASpoXK6Ij9qKRKpY4c4oKERB5ixp4hqQS0MIJf0trXVLj4p02+vnZdYnPnImWIfrGbLNTavmGI7mIrO8sjRhqpLN+Kr9x8mqtftfPzWrYV7jKg4dJRwAk9Nl+NrYPIXp8WySMlTDH5N0ixdAxcSYSskrtwOfpMlFei8j2aybT7Xvq1JGm3arO9Ay2pKv9w12D4wNkRa6d56bt+gfc5TuqCAWqKWGjy/6SnOJ/fNeEnSUNkIAjsmVK70rm7use0I7dpgxY0FKI7eZS02PKb4swAYIbNwqPii6No8xPmOv0JPd5fI1YmGds8+77FNZLj8lQnbdRiI7bGVBQQWEczmr/dub12UTHfBF5moan5YDhyz6TsyYSY/cQLymVr5l0LsxfnSgVseeVvb07fFQL/Pqc14jSj1Wxz/+HfbmVJG+pH4l2NuMRdKlpfADTv/5NSrhEtUUZoURpOMrp4iV8fgUtqv5R/IfUEwGLsZbgpd/Pxmz55gg5KHkdsJzNCSs2MA4TMfqhAkgehrSa2rysxzjMDmRVNDucCsRjzvjcj1ZcLDUYcf1c4hR/IdOhL
    username: AgC7sJvOI9YU4gMP17M3/CsSOmzfqDT8BlOU2tsGWB6+UuTycoEiW+FRMZt0ISX45VLglow+RqOt4JMxRFEXpQaZf5T/nI5RS6N8cE0h2qOJu9QLcibKjMMFsN+nWdrm+4mj3f2qX9VMXfW2WCcfVddrMq04K7gezA+52l7PDTXxJmR/nL1tXh8SUm1iyP3kEqVXCPxQ/zL4H0tSjRnQRM/bwmzmCfRMFVKWM4S+n0HD61RTqHrzQYukdTUID2bLuO7VQBelTrLXvaDy0SnZvNBuzZpRwRVzJnibLfao6K9LzL8S+agGeiZyHnf/AUHt2JbJzArVMMcymWKNBuu7If9SomiKaAM/e6aj2jIp/NCndzNFJIrW5oW2pNiPXe6gW0Op4OCOaUSuvt0isPUGWaCrKWo1qBhN4s3QBrv7Dp674Euav7BlAGoVV+13mWLodKXVP8pr6EZmlIUifxz88AntgIHFAF6dGZn64OLf4uadnrpSmsVzGF7WiAKGI56cLE4fcLQMKWngETxlEUVnm9bReja0SB9+4lPYxTNi8q2UV7sRinbECAVj0zgW89NClq4J6NnVKphl9ILjJYNi2ZP7m3BtWgCPrWyCNEYb01SlzwwinCmQAYZj82O56CK+CiabnZsGXZ1JeO7MPbBLXoT1uXqlParAxF217/JTdGZj8gCHQ3ex9LsX52hpCHhxhuO1KtxVR5g=
  template:
    metadata:
      name: immich-role-secret
      namespace: postgres
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "immich"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "immich"
    type: kubernetes.io/basic-auth
