---
kubeProxyReplacement: true
k8sServiceHost: 172.16.20.19
k8sServicePort: 6443

ipam:
  mode: kubernetes

encryption:
  enabled: true
  type: wireguard

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

l2announcements:
  enabled: true

gatewayAPI:
  enabled: true
  enableAppProtocol: true

operator:
  replicas: 1
  prometheus:
    enabled: false
    serviceMonitor:
      enabled: false

prometheus:
  enabled: false
  serviceMonitor:
    enabled: false
