---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yml
  - ./gotify/ks.yml
  - ./gotify-bootstrap/ks.yml
  - ./gotify-telegram/ks.yml
  - ./gatus/ks.yml
  - ./am-gotify-bridge/ks.yml
  - ./vm-stack/ks.yml
  - ./proxmox-monitoring/ks.yml
