{
 "title": "Proxmox Resource Usage",
 "tags": [
  "proxmox",
  "pve"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(pve_cpu_usage_ratio * 100) * on(id, instance) group_left(name) pve_guest_info{template!=\"1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes / pve_memory_size_bytes * 100) * on(id, instance) group_left(name) pve_guest_info{template!=\"1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Disk Usage (root filesystem)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Current Disk Usage",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{job=\"node\", mountpoint=\"/\", fstype!=\"tmpfs\", instance!=\"proxmox\"} / node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\", fstype!=\"tmpfs\", instance!=\"proxmox\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 18, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{job=\"node\", mountpoint=\"/\", fstype!=\"tmpfs\", instance!=\"proxmox\"} / node_filesystem_size_bytes{job=\"node\", mountpoint=\"/\", fstype!=\"tmpfs\", instance!=\"proxmox\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}