---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velocity-secret
  namespace: media
spec:
  encryptedData:
    CFG_VELOCITY_SECRET: AgCtWXI2p14ttcamVk0F2mOqwen3h9i7QSjYNi5AWsXtERImBR8fiijESZU+rnKA22It23pN/9s6UHteWt9jcVum66LWODVEKagTOsb0VjqZAmjIgoL3ofPKIK9DK+Ah7k15JBsFHPwlWKzt9doj6wz5/pwRdLebmRBMiiqoz8dDZJxPbbeyRx38Xp9ngs76CpGLVKsmaqY8U00ygwplsz8TZ7dJa/anHPHDVKx+N0Mzd15IQMnmUEOrVa4OlBnI8HzUaWG7VSrAfZZu6B+PY9bDUarCMLS8wkTB/ug7bHxWjNclTIyyXcs8v2Pn2D4/S4FEnqyyqwu2V40pSJlVJvcQSyTJYOGKp3uC9U/yTE5tZ4ZMAQU3yRAKnBFeeYXloK6L0XTwjpISLUyxQf5ASnHlv5HcuqKUeRMBXZgRwK5fLXB5WIMRaXaax4AqBFzI5ZgPWaPx7eByim29KSZ/uVqvV8z8NWsFQUWyAuS7mbLmypgDyDAHwASzGoWr/Qn28oyTCdBgt6dNlFxKNwq/uZ17h5eM7/csGmAcvTBHItzqprvEAA9KApjzaOxxDILodIGYYpGCGG2Dl+gbBCDonJV3tyh9sZehNlCrSVxf40NYX3Sp7unOIggkaNmI4FMNFLGMzjSy+n5IkfpBAmiKr3cskJStUBcg6awn8P1AXFjnOzMxxWT2o0yI7/tYLUJLtWnAgrDjnD6exaokdmFA4WFlHijscejJlPhy30J9mb8GfArM53Gm6f1r5ggO+BLysPs=
    forwarding.secret: AgAid9uI3uju0xeV6M9ymLnWGcES0ab0Jf7gZtu93vstOEy12tcg9Enxq25Hys0n2Lect+m8y/AST+J5sQhk2AVQmHif1IIxsi7Sau3YKx/jRvgmbkz5ekQrPebOARh4UtUcpFoRLo6rXvY4zUyE7wZpWggbO1/MnZzSdBAsaMLxueM8le2LoEuhcebAtdWMX88mEW4Q9OPdUehfE9j+fIuuimdIR9/tVxQ0KO/Upb/vQxJmNHCSno0IP3KII8WOFOyrdyvrV4te4tiF+XjXjcwp7ZxDb16kHVYT0tDUgqFVRGM0Fh6JpaTbJrIfa0twkCjGmZShTOmYRJ+tMHd4zzoKVq880QNE3hvoxGssfqq7gQdrLvJnhiQ6wOdB2O2QnOyweR+BZdB5Z/cffeB8FvfSya/hpFAil9Srl1dDySRO5aEaXLio1m5qZV9elAP8pX0T/3Z6BSBzQEyTKkkzj6p1ysu1CZKoTgdhDgPSH7l1NztxKQW+oUdvdhZL8JhCxM3DstooEIAz3I56FCE/3JIHugpf4v6ThNiyqkMrzTyPprAyWDJlYKHmAxLMD9UeBQ039UNXYVDl//eq4RAU2XIkF1FliPBzicqJl3qK073l2Rj61At1vWCu52qBvbIGrbM1KeYIVQiDCZPRjphYBaZ68t6gXlYJQ0PiXenxg3e1owinlykFXQMpiGV9P3PEBn/g3Gfn9Lpd8lOQW2eC/z2yYsbvxRkNc5bdVTFRKlkRCiVNws/FHnuOHKcEO2d3paE=
  template:
    metadata:
      name: velocity-secret
      namespace: media
    type: Opaque
