---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.7.3"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      app:
        replicas: 1
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/sonarr
              tag: "4.0.17"
            env:
              TZ: Europe/Brussels
              PUID: "2202"
              PGID: "2200"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 8989
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
            resources:
              requests:
                memory: 256Mi
                cpu: 25m
              limits:
                memory: 1Gi

    service:
      app:
        controller: app
        ports:
          http:
            port: 8989

    persistence:
      config:
        existingClaim: sonarr-config
        globalMounts:
          - path: /config
      media:
        existingClaim: media-nfs
        globalMounts:
          - path: /Media
