---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-secret
  namespace: obsidian
spec:
  encryptedData:
    rclone.conf: AgAiMpBq9QNqsD0bvR8wpZFQiuD0tGTXxzs1scsyrsD0FmpcEwobNsZxC6i8hrmLisCG/mY5BTwgIrkTE8cwBdqcKRK4TFIK9bV6GParaYQJDxG26DWQO+Yy1QLAnq0YZjzbW4FxGGXAMR81zxFhM8bRDlwg/twuTULJdSavL2ot9iTVXEQAn1Frq6bSVwjzxnRYB63C5c7eXRtd39FsJUt0rKV2ptbhASpTVXUPdSiqe8wvdpMpQH5xg6K315jEfJJgjjauvwdmj98/Ij6dBPeQD8Bvf1Lp58nSnsBN5VRAfQYKl+EjJnaS08OPK+REykiRWoDkKr7OBnO3kvlpuczHfL7KYohVjPWjsTYSErFr6dACKSPCB39YyM9ROc/5eeEY85kX+KZhtnkIdMiPbo830weQIyBkBoaoVZQx7QgJqvWuehGaE2s1keloGXZ7oyM5Hi8vlENLfZ/DJTbX3puofYgNqNWyNVplz35CCiS8so5K2EAAXR/sLbtGriq6jX+44n4A0I0NP6Ca1BcncpNoiMZlrLj6I/m9y813fgR178MhFZtt293Ecxp6lutnR62dUzDoriOXdWH011ZHPebCgIRMW8CgcPQjsepCvCy3N42LiIKoMt+ZaLIvRRB02Sw/kFXGpA08H/wd2KxjBsgbMHk2FELyfUVXqJ5RZgpno6rjMK48+az6Bded77ZalUY7VZ0rLH7WKPPlufKwa6L3VCg6iS+xqVvaacalA3KpUSnCCc0qgX/WOD3yUlHnzhiqUymMgf+78vcdwhizAE7yoz3ItKVqcXp38rfZTmcDXjoV8eg+1iuL/FXidd/KFQRuGTM5MHmsZYBsJ9tfxpKfGXRvT96xavYO6GtpgP/Mus+NhqcRUGlaViKRbBMPoPML+GnYBL4JudJ9ZVJR18eDbjdEwmMMcMKHLHlYi41vXpgzd8p9J9dBwQadN8zgtzYf2xNGaLOc8hCtVoebt4g2HyG3+d1rtS2g14uTm2qifa+V0sot3kVwJ0hTt9o=
  template:
    metadata:
      name: rclone-secret
      namespace: obsidian
    type: Opaque
