---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: obsidian
spec:
  encryptedData:
    RESTIC_PASSWORD: AgAIJdba1CrylMrWU9npKQdtEOKFDDTeQRqEMVX6NGdKCgot6x3HS6MnS+tsq+Q+pF9dHiZ1RNMwFQ4iza8+8YtXEp8q6ljxJ6Ww3I4tE9Aex62NSA/dPUr4dx+3iHy5J5JSw+RokBg1Pjk8Li8YjZss6wdr73QY2hbfzWYiWHG4+iyYm0Kyg/K+FuuLnqedphYANaoopjNcU8aLtSUaFSWLzKEttdWVR5rrYtosHSOCXuMH3P7lzK4XzYWuJhJTFN8z2lJkPab9oomYyEHMKVhHnruDih4xzzw9ZPX3JT/rbb8UHz5+AnhQAS9YB46S/AfsWyg6rLwwOVvZg+tC8/UM1sm18G/4q6KmTkpQ2fQwvSsVQRCgN3e0dpUAES2Ovp+VjM09C/blOIZHszWI70xWZtUr1/TZgESUJ6NO73EY6hq67P1KyRWXAG/tCliMk4DTrcyQPum24XXWRRgHPq2ZVGMW2U+LNLcP3EmyJf9zuorSly+MR9kGbrmOQMcQ0Zdrrye6h3eFT0maV5QQySR/S/Fy5RXAPMBr3hBUukO4F4vEqZ7+lV7wYGoqH7xneqqqU9jo/fzOQmh79jduGwYvYpL5QPtYUP9/PFNTkk2KCuSK6/9Vo5vdjZbP9jiS3+neY9Q9zwNq2p8mg1H/2dvuS4vLdhp/MIkf6LcRoKHmq6t+zgYOqzmzoHK8sdPz+XC8lgMGDxuBafpXgXUBn3Q+M4pdPt+lBzYuC2We3ubSIEE=
    RESTIC_REPOSITORY: AgDDYlDyHQK78uOzgLF6oYmG8uNnkjv1sMXCjwEMW3unkt/bXP87SJPq6N07ZA0FKThQ5PXNeQYglGzsraocaVgj+yPR+UDuOoJysface3xIJDQDe2Xh5Fy0ugTVgstsrzYJMgwOJwIwyesiZ1PGrUvPC3DKrPGIoDjwGEdP3ioy3CraKUmW03OVsLlCnjDO/IyvU5UDpLScc/5zvG4Dfyu3onjRhoiOryz+psU3a6i/SbTi2Q+9rc9byc+sZzFsLhRmfs40pkF3B8RdX6Or1wDTyNMTqG5nqkLBdeid6piVpvXcNg95D9fZL4JVRM7IV2j7i4cvYCJa/QEimTTRcqUMyfnEViFv7y0VtkTqzoqtsfwqLrk+FpO1JhmGPciiwXgAKFACi3HqXuTeILNlGcAxncDSFnNEfmm/WQ0aJeuQly9b7rhy/uue3umBAk9sSjWWTJBE5ZUAExhhdd31w8QO2m2Bb6x6dxlfw2F+UmZ1F2KE4yh0tWrqXoU8/orrdtod/VpqtStpdelMW7uoc4A6XJ6p/7XT7U41Q9mJ4O6oBsGpS4YB9WhCEYuXLSNVBqRvLYQ+f8PiyTFaSMIWdvOivfyogwQWiJSXbPlPdFI/KnJhF+cvMz5AZTYRCpompmwgQEpsW4gar/2FQAVRqMPxDqmxT4+NKzjNjhTk6cZsXd92HAMJAqHeJfhrPKItIkodRV8nX5PqkJpNkUhdpmdNS7WyOiSDIingAfPaunlkrHr1nPU=
  template:
    metadata:
      name: restic-secret
      namespace: obsidian
    type: Opaque
