---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-role-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgByN/xfo9s+Ccd417P3lqtj2gVhBNbwa0fax0XkXIi2w9VwpKE9ATfo63UDcptq9Y2Exp1TCMn0RinSyENjI1xfzBARLzn9MZi65yMz2EorF4aYd//LgJ4Mbb6e125R9ELW+D8pGGnbz4G17Ni0Gg68S0cScA+z5Uxi9bsqNyfjCoVgu1XJ11qqvFbPFBSgVKp8kGAwHJjbo+6rz/Qrdfz45ENc4pX+l8ZQwRzAz0pXOOMISsfRFF7vXN3n65ytZwdHjgNi43ZgF9zc5RNwSYrNQ1xAlGYquWadYjZTqXJHxy0OoRcmZM4wU5TU1MRMbVgyMwDJRU1E6xVFlUoqff68fegjutiYYnJG0ZXS8uu/RZQpeulBX8yZ04QR194JOSb1b/KvQ72DvMSGOVw75M8berRMFS/tWxWh+ZpQpCs9d7cQchqI0r7RkAIT58Hz7ZJxjOSCWtoLsSZstpMKUQqyygU+KOwAx/Ig5l1MWw8MqqqgXepQTa+RMozACI6swTNmNUnHAcEFfHYX3+xfPn2p8XtIZSIyjpEWgSH9Ho8mBLPfXrUyUpB33yGpL8km59E+T36yTLVbXIUs9UPvrN/emcjMWMdoTpD0j0+47kkjWyWLNun6f6cKeDK0dtwy538j1SF/y1ICZtW1BuFfpd6AX0Yc2JXkD/3mREDK9TYARwamSvMmg/XLO/JfaQvipKoSO/ELCyChFdFym9Q/In4yeI+vuL7fwgZybcOogBS//9FHQDM6gLkXuitjmZozBW6daA+f5mAlg1zgfILf/YOi
    username: AgAwCwgaVSwy6s98o2D96JWw6pjsiZkrvdObMOv+PU0yIvUB3B1VvmF5xupNQM5OBi6T90SQTu7rIXz3Ioo3MRPX0oBj05KC/QudEbdmHTv+/lm9iCqXVb7efE7US9wTvHlNo9/wuvKzvWqHfGxMPIMe4eOFkZ+ohbSosj4WzoR9UOB/t+iaF6WWsSwtW6Qa22NOr9f3KO5DkaSYpBvKp3rgbeqqvzdYX1s3sR6mKg9PcFYscx/UWGQapx/JebljbVcU4Y+9cpwv3Re2H4e/GOuDZVq6f1g+p/aOmNfJNMswYL88OFk83bviBIvCNvdhihQ5RvNzX36nsZKs3/UK+iK0P1DDh5dV1/3WCWXnfL/4f1DhE4sk6AO4lC3wlkDBkg84N/2RDvYuBNIakAWHWkKwD1tqTBRo87KDoh2lepYNeGCS5CCoW6uCqN2anQXWCow9x0iYIRjO+HumPuRC3+4cMjqUcYBRzd4NRIPyvdSX7iVF8MCQe13p76eXgZ25LxQgPeQYV6zrstkBT9ecJo1RPlgf7l6scOnq/oogs2ycNl3S0nImxLn11QOlQymmZTJHoVz2D0cfsiTMXGH1J2y3fJoyvUby0+VLfnRMtl3NwCf07hcbUofw0871xvYGZAlM+8NvhdbLJcQEZz6Yv/uNXGzVIBIYHZn2SkOnhfXRnCGItzUkTtXtHRi1uNZI6dt7xxq8l4fe
  template:
    metadata:
      name: zitadel-role-secret
      namespace: postgres
    type: kubernetes.io/basic-auth
