---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flight-tracker-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Mi
