---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-helm-values
  namespace: gitea
spec:
  encryptedData:
    values.yaml: AgDE6ZJwwc6eItBlnzT41EVbGtgCfV+MyyS6gGRuGHKg6cegAzR7Zo7HoBhuXFVa7wz3PJsF+hgkDYKwFnjs9GtmA/EDAK7bgFofG3+cQxjxN0UyaLLjY8uZbdeGY4IA0/pOVDLO8Z6ko5IvY7H9h3FN5bIpJcqkMD933JomUuQ/8qGScTI06RcS9BqjKfdphqnpvgQx9gfzYGreb17W8FdsVadEM0b961Db/RcG7v66Rr7bbSaNb9E/4Z23JiN7XI6CQ9XajFfY82klK9Hdd0+Kay0HC5/BgmjyLRGvHLd3xqgdFp2gWFi061OZPmhjBDmkllekLL9xW44QMv6mixcMfxq3fJbpxVm/wa7YZjbbCSl1U8jhUbj7QIgDp5MYpc/LILlXR95w1gYQdJak72jTI2CavGDl6FZwAYYkiIMT/sLAziIGIF7CUL3wAFRHXRZA7sxWPQbUejTQ6EQ7BflCrLb6/9BjB3kDvFS7uE0JOhgsxvdQVQW29226uDXbjUYB7J+twXDq66WRFQmX4oG4b5eWOmMyOGbUQX5g+S0k/1sPZa0QsgCHHL4NbmdA7BWR6DU9WHbmvS2xrQio3BkEJwE31HHpZe4W6qGW0w63M8/ex/GcjUZ17tyTbJh4wz7Oy5YI+rBWqh06SEz3o67KJJ4Rsyg3b6RqZMsl3l/uDwbi9loiG/3b/UF6Acaw+6i0IMaE9SpPohFi6cYAAUdmLRWbwvM6nJrOuiac+gf+LjHefjYBmQg6NUS8JU77GEMkJQ==
  template:
    metadata:
      name: gitea-helm-values
      namespace: gitea
    type: Opaque
