---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-app-secret
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgCA2+kt/foGfdmjOpgDEGSaDiWLgWX/rgbsa6KUhFOmsNl/8UgkqsLKbQ5LZAcElWy8055PWDHFcPoz9Hfi1JWqzx98uSaYa8GJFJi0Wb/lyPq88RlPG0gCGzA9ul66T6nYngHfYWqiyJA5DA4A1w13MY2zA98Fp1PctPWQQVuOqOsRV3fGZZq0SbNnUUkqZ4Pj7KjP+VCZGo92Le6K+HaZ4Zez6eKc30W56ei8wcnMm4AUjWlUfP4cCZOrDz8Lw1shrBhTWhAV7Ke3bvVTQ20IPaGVYwedPunfV8QCISUvqrbOVn4WYLA0O7tfbARkXqoPjqRyKmxWbboHUaOO3SzNdPqpTW610nJvmgequtpE6sr5JUdinNVVcMAHQqouuojDdJnSkpidV6IjIW05DsuGkJSNOvsGDzX1kIwZQwqiFNi9F14q+IFNToPn3bQTWi6RMZxct+LjfIljha2RIi1B6CTOBZYz13SZdPW9l6PL/H8cJFYk7l5Wi7OaqYyvWP6XZFq2N7Qu5eNhCkF6OMTmw2Aq8FHttaWoje8KzS8bWQXuRC3tTZVlK0p5WD/1zsmFkj7+hU2nyu2kXL6Z0JbkYxgu8EkepR7dKlRsp50h0sZMu5xEf1RwZ2eT1J+KLgXKnK51QcZ1ffMJLcG7BVkaiJqU7P8Zo48emWt3rZAxhsiuh9w7WvNbck729DvaLtGB/DTHcls1VNfDGg4RIeRLPs2ucr+FxBl9OEw7bui7U9fIKm20VC/T+fZeh6uQ25KJFa2xlS0htgooM7pijUcf
    SECRET_KEY: AgByRertDaddGYfm+qdTeKF7E4McuAsZcBIENCJ43NMwbzN8fyZQej4VA3RUVjrag1vS4Vtx246gCaXeJJP4KCigYfNXqvSmrrPYNT0Z5wnIZIvEn+Kp8drtCScGSJkdmwZrUN+n3fNnobtt2yZj5CWjiFPAELV3o6qcNMLL4Z38c0a8rOiuPfOcOKV8YBdrf5SmI4J7Nipt60mWztGm/khc25pRvOmqA12aarOHavoDL/h+tKO+/ewW9m2C8QzFeL/mbasRf6JX4j5KeLx+i0ESuZ68JOwxy8PLLew392TQb8HE/GZLCE5TM8WAXgVvLKkWLulSkYCq4gaL1DfsfgwGCK3VqtiVzZ9rJDVgU36qhjeLB/+X+3qMWk5Rtj8nQcRPpHZb71uWFsCF7hUSECzC79UlAWSFVY4q4EsMgomDwuZt3J0RpiWPKIx+L1rdQrtm+6AhWNYYREuEJcQHlaNCpbTj1cdPSFMKXzUyOl0580uiHzKbezN0DcF/rnYFlpssEW+RH/lPuQLCIuyqJn8JfEjs8siCnScXTX+dfyVHEs3b/2LQSmpfNvlj27xO8pTbLzHndbu+UUA04moYTB2KmNhtEF1d0daP15/EZhuWIKvf66oIhZvQYJxNWJeDcR9IPXZHBbbtIH56ORdvQyTeIhaw7P/uUdR5rJi1qk1iIkznYfMOTGB1pszLGyJa57YYUSHRgwGn4sXAwV8T4BPZAsoCdrCBR/IcX4IjbCzdQWeHG2OlcQ1XeE16Unz9oQMJ/HBl9StCW95QzGaq3Hfb
  template:
    metadata:
      name: immich-app-secret
      namespace: immich
    type: Opaque
