---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-app-secret
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgAa3xxEdh1SQsMNbv3EsSlEfSGCN1Jcs9VjOm4yeyMF4X9GtZam7NBsnmN2l2JP3TBOHMmfq9Su8j48IOegIXYavvAzgo1OurpInTPUt4UecHIbndjiXvsDmWcvBEiH4BQp/Hf3le5YK3tf5arobWNefj5BQOyXQI0M+Wtx22RTEcEFPEiapvBNvOOJydwiE00pnGlQQSABzHMomKsPT+5HMb6OGntFSUNGGl7anFBiNzVUVuMGhC+rkB8I9D3zf/V5D7toMsPSCmeqM9V7N3F7+FXTCrdIa/+AbSuZoJtk4Wx3SH95bX2eEIP8j5x/pbVDnnL1TZ5efJGI7ugS5TASOVJqyP9YXBirXYzxqY/bqz+4BX1a9kaRniCkG5HzbtQfRQGMb0FdzpMjLTqbED3PAgzurRPDDHkX7Ov9/vqXpgX1cf/BTX9vsBEe+bMVgP68g9SnO1D+58NPtpTXwcjaynb9GM6yOdYdEFDcPqmmxOM4h09rjk4Ztqn9dmkfmTX+QT+Dm69Z0b9toJrtP/OEvPEYTUBlMsNwpUO2rK5pFauffy+AJrYy4LKKo4G9G1b284YaDohuLyOO/kaVeG+wZfOJ0NiZQUYSHunoOn7rVtfeqvUJVC/sNU3XEx63EBb4WtBC6aD1mAAuujXvDkmBoiAs3QzEPmUIPqzO9DXRlr3h3yNKRjxBUkpYJMmBhWs1uBkd4bB0Mciu8mjqO529CavJiAYmtWZc9/ZBJwhVAh/k9c/CmU+b6m2jaC77SvYfjeVQng/qn0Eo1dQbX+Gu
    SECRET_KEY: AgBP9FSzec8RkvVWtwcGiWplrf3fUdpPOoAe9R0J4QWkFxOcfwd+bokZ2AkL/W8FtP47INDDK1S2Pr62MohGmkKOmQsnPp6Y0LrJBeJNrvO8RH3vCjKzMfjZkfT6VVTtt1C5LteA/4ftVqVrjDuvoRbVpMbzYF4z467RwYqq8Zm3N3/ugEZoK15lqtlGoFaI4PPUlxvYcvIIlUxAUmVeoNtdczMh9As3z5WUS9qPZLqM8iIwdfMZocTKzMyK/xf5cIVfeFISVqEtzuNUZC+wxSR0C2ArGAb4KEZk2QUpcv7gMVhJ3EEt4e8jVKDdfvr9++okYl3sbJJS892RsNHQNz+0JzDbMVaJvghecedJDm5L85n7209EjT23fYoCt6nkMk5w9eWe1kleZBAv4ZB88UpxCnuipr7WuFnBHvDBGpktzU6kn4LrDo24LQjJseniMkq6dIqouIMKqTA+MBhFuibxY1QA+qpO0KB82f7qUiRpUXLjIXfZALIXI3JihOj89+xPZyak2Fd5B7ZP0SPXK099XVX6OR7JakyVgSrhpzaBormgXs/ZxUD9xOoqcb8zBIU8tKUmfFZeiklViukaue16+mufoGce2FV9WwUPyapWkwqWw9XmxnlF9gSJXiJYnGjXAFi9nLX+l+7aI79o/JI61cC2vHfW8ttYoi02wuu7xT2gdWpOnX2yV3fyOi/JFhTFsd+KnwGXVO60dSN1sjQbQAok7e0/c8L4uZ/wlU0jkFz1W677e2kQU3kGpmYxer/yPePhu5psaB7BBs1ymMhg
  template:
    metadata:
      name: immich-app-secret
      namespace: immich
    type: Opaque
