---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-app-secret
  namespace: immich
spec:
  encryptedData:
    SECRET_KEY: AgCUgEHgx9KTVZk/jrPqE7cIDeIdxrBPbWdTtlvqtpx27V9MaUUP/Oa08pVC/OQgEvnDLx9D+itYaevK05iOhYt+P/VQOjOIlfNejDIwupgtnKcxD6YYj/sf2CU2uYCSiZREmi/eBKmhZMkFu1/t/pFniPr0R0pIsXB4czU2zRS1MlGKtnScqcrSXBUXenNq6Sc7jL3hNY5q18Wdw4V7X0bGZ6peM2QYOSN48dlVUO+29sWnIMJXSxVyr+ECioUnZi6Pdh69e74Tf39XFl6TJZEpxgZy5paizlevzNHvulhOm2664Dl8EHnvy/kGHtriLXqQFsoDoz9yndvoebhCRXiVkMXqb0TcO0RRUua/uNBzL4mu8zXACDghR98YRVWQysDVkOGNnBqJJHea8XkLkZLCDvIRFDwqPlWCW8cgwFDNT+VMSz7AYXa9KzLJinZInSxf9skNjDTEjTnEGyvYQk+r6oHVBnSdq/GU0oJYGrx0GKIDGz8d6ux/XxrdMklAXU2X5bGNSmg7FrVgfhQe6mt2a3a45bI5ykaDgW5bsJhqXBM5WrQGp5P0KaZr6nH4owsATGixjvpc72cj/qcfkOykulSO6LsxmgBqCMolebgdijvlR7dzZ8yo4wUEytKoKdm7OrRmphR/eidFir7XEymDoNTb3JDhAOjs/4uixEDgLdL7+xxd5NMql6NdDIGzZr71blbMVilB10BeZCDt67bJdBxgcue1M6UKmmF3HnI2giMqbRo/TZtLHWW5Ul7+KtGzAKihqarCKx5CSdBBW4QL
  template:
    metadata:
      name: immich-app-secret
      namespace: immich
    type: Opaque
