---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-oidc-config
  namespace: immich
spec:
  encryptedData:
    immich.json: AgAOtmV6HG2zE2JoJvDhajOwKMaSgqtftDofaRfMlikcWVpfdm5frlpCUbJhuNBCIaLvMSi86T0ii+vrwtOPtMkXx/lt3Qui4pFkcatWg9VnNgguo7xtOC58DBrt2KDRoIVqNyXCKNtDxtKMA8MmHvPeSl/8Mhzl/Q/5t4hvqe2eFxHU3IzWbMMIE605wiiZ8+spGfSBQqwj2LTQtRMWZQUGPSFVKXvdWKQt3YAzku+3tuZXJ1viQesxmNZmQzX0rjN0YQlEMGLkreHiqON4Y6+753i4c+UDAEFV7+c69H89v595mqfJVu4tvDfQm5jXeO54dwFxNsmRgww12e+53IiCHaolSDx8biY76lHWWMaTkS5yXubehY1hgKJd9uzGNJr0Jirm1amLvGVsmhMXXI7qzl3sTL7b2NfS5r/ctdMHktxgmSvzg2jE6FwhZqzLeyIqC9CFwFhy/1ET+1PFuKO+gkl6CIfryCbEAT1Urj/Rt2VpQ/W7wPdHQW1zzK7umyXLe/fmpV6xAFwJSdN4mMNNoAQFH1J6B3mgVv1jcd/o9sEILykl1uzD78spZWfcXQDb7b8r8MB/w7C0YWDTBE5k8V3UFBedHIAl6ABZxKWcqx8+FJImGOTYpTjfxeMXAsYj0szvVCkzYYkCAtGqfdqlIwuroIAT626twwB766kovbseiO6SyfjUT0XdZ/2Zlkv2cy9cOCdRD3NNnou53YbH3Pz+A5qSrx0hMVt1x3ehmYbA6Tu5+Rb2CnrishwX4HW9b/G+cDbyDHiBvxbsZmLlejaMH3I2uZVzKfjdP6T7vX+feHpS6+MF7Fnp6+0RlIKf/9UjswEm/PRChDMIuHAOB7LAXMVTyqehIuEvwxOZphTDjaP17Esa5Vzu0Rs4gc5uEmzD6dNcd3EV60DS1SYzzZDjwbRE+pZhwngADtXOInio1yCCFCbWae7mJCz71rLkHhMTZt4hA7AUPAczKUiQ8nvxnpOBMQpCSxcJnxvNhG/F+bos8lFi9430Ll1R9aoZZamuIzoJsYQrMmVjOLKzn7N3Pxlp6P+rwvoIoyMzMKAC/uNcbBTwp0wMUr/wXj/XXeiidH3zvseS05o2OU+DMT+0UGmbbzDXx3rnWkOcLTeg9vXJaAp2ov/ar43D0y1Ve8SVpp7QnXsxSDkDXywtdwbQL/hSvLBLEKyl5UWGdziLTwCKAGT/tCGevzJXqAOq/NvaWhscPrXTycwpbpEWHLwBHTzQ1//S96bP3Sie86A5B6tEoj/1skhdYYNy7IxI6U2J79HaJTp7AImI2hO0I0P9ir8fujbbyTjCAoNYfU58h5DsFD/OA1nMTl+OdAD+XjUtgSZ47ZBM/qYt/o/YtAr1+n0tXb1rr8mCI889
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: immich-oidc-config
      namespace: immich
    type: Opaque
