---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yml
  - ./minecraft-sealed.yml
  - ./patches-configmap.yml
  - ./helmrelease-valkey.yml
  - ./helmrelease-matcha.yml
  - ./helmrelease-vanilla.yml
  - ./route.yml
