---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minecraft-secret
  namespace: media
spec:
  encryptedData:
    FB_ADMIN_PASSWORD: AgCHDDey8LfoVfnWJXLQfTunaef4L/vQJzDv+KRNv5w5vNpTxBtdtv4pkVkSBlQI6cr+oKj4LxgCvJ7ku3DP9n1UAMsvjsh2MxZAMLAJC3yNjZX4tamCjegI5QLv1DA7yuIGiVU4nqBE8IByxiRTL6SQUMmyFTzMoNsJcrGNk7Sss1SeFL+8jA8KeVPe1A7rKC34zouujvFkHOp414dJPBZ78qIpYUo9mpal5/uvjs0h5n32OvUZn5yY74hq/aFejC4dai4U1y4VTuLbzL52clx+8z6k2Zt6/U2fsxs3TL4enjRaH/nYIvvugVOt56t4PjjtsaHfGxoQQIQCIs17jhtIe8yYbmFrG2PebY2q6b6vFfjS7dV5U9oSDBFklnQgy4PYY9RQ6SxZEGjL4cPBdO7G5Fpj5Io75JkXhC0bN14NeyLxuXn1Z42ifdff+mrxooSDtDdL2GsOveYYpPcHfX8tmzkE3/pMRNS49dwBcBag4t0Vc3bGcRAoKFuh1Vz7ZPj1LHPDesiGPbSRprZFhXeWqLLIFq+aUv4Pb/wTvmYkXoFhmDjDwE9pPMJVU+qSGV1fP+Ri7pwSV5VPDBosBuNYvKOow7wjrHYZH/j7SkIduRwP/9z+1QyiC7FL0WyyxN5cYzh8qUuZPSnP+FAzwH5v5arHz1G4iGe9HDhcBbk+G2U8f+7TP9+WyevcaJ9q+cR8gUzIDgxB4T8zi3kMh44GHI86URsNN3uBbdWAlBPv+w==
    RCON_PASSWORD: AgC/pPTwD3mliv57Kk3YH+v4sLj6FN8Yr90+OEzd9Jo82DIA4jggv8LYLrJ/Mzgit7YU9uahspvzoV4cHTkP0FoT23gJa9qf8Jp84ePwx+4Sjmsm2TPCClCCrVrzpIg13rYnhHhA3Qpg31r2cwB+yImo3ZFik6p+7QXPzB/XS3XlLrvO+NKpx90QUUi5U51cXPKSvxpbmOatWzyZfhPf84plAAlHXVV1hmGODr8R7iKFvqkme3g2/hAxu3kJlVJIYS+cGFInjF5VAc3KR7+0py5N44r6DMBgSm2Qac7coeIvnKrn2JweACXA4lOrC0rUIZfZGAwNQxcpTwleGo89TuoLbd81ddscnnKRorZvJ63KSDps9cvik+J/hG4RqmRNUzdPgoumAEAFT6SIpSJpvevRU092RBqAMaooc4ZlCE2JoXWdcY5s+6rXDQiReRak8QFKvQfZsLxYm9OTPktDdCnU7EK05G1gPzrRhzfUh7xsPMg3Uph7KbK+w6/mljj4fYs6J4XtMd4P+l6kUDLpD07Jf8bTDOwUOeyGs5lmvQ+YLxZCTSoWsgICQJwCdQi4t0/+X772PRVUv15xv6GEpvfbEw74++xDChsCf6ZoYw+6qzlmqqfN1BCrtyr0DT6OsU6S5KXfLENfbG5JJZ30A89iFaf+xNdX+rC0qFk0tVYTtj+jfStZquUd8BGKBXB6hOBfCkjfrKOk+oNLIXTIqpDGyV/tSPsf3NHBn94Si/0B
  template:
    metadata:
      name: minecraft-secret
      namespace: media
    type: Opaque
