---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freshrss-notify-secret
  namespace: freshrss
spec:
  encryptedData:
    FRESHRSS_API_PASSWORD: AgArQo5tOrEXC7BntrS3QD4SMU3XXJZHb4WzTlZ4PjUkULLLpd6QrkB/pHwoixEKQxIXqpzKS10FfbUyjbmWGTPKxAelVkkDDZONUf0t2+nTA4B+Zi8GSkFuXIVXwdsie6trxYKbTVR7YJbVkr7OdRNuo83opdcM2aiXwS//kBn5Jlwt4M7FOXInleMliZgMJj3aKivw8fRNXC4TeUskPGaoktHN31EtpqS16ReGpWrKaHA/V79NQPSSNcsjsHyKSOpllHS6Sl2RRb12fpSuXljVi0aiH106tTqtcvuB05pIN0UIK+rWBP9Tf7AL/LMrf4Xpvnc7EXcTr0UFEf17CWvhADpvUWTlOZrGy5hsE8/+P0831xP4emra0nHXd1uWbGrG4EK4NysW/UZMJqOPa1obWTErvmNpROIrNjjDNKV2O8/j26ECGD1nCuf80Iw8oTtHiwDJdMAA9xS6rJk/38PL5BOKfl72xGVPsZr5tNsmYS9zzkmfQzo+jynP7nWV0rOO3OnM980jfRtrUfQN2PorDl8567RrADkUjOjJh81Ck8NDR08ZgQYbq7pbD3oAPqauhJHQea2io3KOeAVoUNElyBcgGwGjQ6GgPPL7XnTunDL1w3yTL+0ylMshsPFhS9ut2bslNLhe3wg6H/oWueP1XhnO8tD0lqfXEWijKs+cLtr8v3FFaS0cJ4Iop9r6QEozpSBW+Ii66O0=
    FRESHRSS_USER: AgCFauBxqlylSuJh8P0P2Ai6y0wEgY+AV6Z8F+8uYkBI0U/8OPq8T9jKDhH75NtqmPlUVEAyjjQe1aBVhXwab0t0y3Xa30SVbK8HO1CU+7lRrrIX4tHi9/Vxq8eCpRByQX1z3t5mKK3TZRxAJ+cTEL61caxQy1t80pe5eS6t+9d1prDqqDaPJqId46+j1szmKrIikNNCPEsrx2GyIRPna18fiWL4ze1/esH2Ds8rCmrQayVwAqUl/KGlXDyAoiMg2r8P2puAqTQIoqDsA0q+5ci0l614AsmciLgAioTDste34WwIAVQN4FYAjTNNqZ8tnXfofstM9xQkD59QEdRUPzt8M4fpDjo49zcclweb99cH73mdHRjOsYwPqfHrFkoFcmgZF0laKNXFxVUKc+lMjjKCW0IpeB2qqIODhChu45w79t+wRdTd6o8lgI+E8NDIxifKNDpyYaJAAuVldZSIw/hH4Mv+WYVCahFWxYzeaQJiEazYwhUA9/3mKOAPDtrpNmEzLudG0ppsyTHKccuaXpTudjPKNS0I3dWu0qoyWCxdCiLxplLYYUMck1KvNlfJVNGoxIvEs7WmEihSTJdOIEpTQD8DSBv7A4buv/QJsZQhv2Av2/n3edHq+nX60RyWqo2u1LmKzmLU5WIR33gJIkeJu5/AvXlfqOu9+Mel1e6ZSXDFA02CiK2QHEzGHQ2v0i4UzhiD/3x5OJRU7aGFb8KdB6Q=
  template:
    metadata:
      name: freshrss-notify-secret
      namespace: freshrss
    type: Opaque
