---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-role-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgAI5MNNhQYrT4odsEYic2QhXDMbyBgs1n1BxDNMLfpXoHySiHBPK4BHmbOLdQ03Jg+5okbKuGwRoyr8odkvOKP1b6mIeDn9wA/mh7Hf4lcBubzgYK3lYGmmtu4UMZQnG0M/xOnoukkw/gwmzxob9axMnsPKa1LkcwazkD+vPS3zbhcVSq9KIkyIKg/HmdrhjRAihAbZskp1zbtWzzjd2XzPyYZ9d4ESvJdWtwTjkDm6rRw4fq1/6POZDKS2e8LzwcdWrgY1YtZF6z70z5uPC9Ry3oIEbXYikT8B4w7w7cKdmKeZ6OAUc1QxIzRNtvK/7WNn+XL2sPHAaSoPk81boYiv9+nBBG2eDJWPdrO+lQxBVDnR5K8w36O33Rh0F+z1RACb/0K4mWV1TpNEozTf1XiBiw55zWySkG8/9nTTA2F8ptxDuLROy4HoGCWk6heZvfadvTyjmRv57KdR37DPc7+WdKcEwwd+0iWQQsEG+Peu1nD9iWSUxGZcYHv+/z8xinIjNjGH2exHWhtvTNWIICkk0HfvodrFZrs9K+3GNm0lzvNwHcad92Bp9IphIQm7atwrR3v97FjQG7DVGfJylPrhs4KiLzB+H9E0UozjN2QtIpXoYV8Nr/dlts7OtWhHibEHyTMnhj41vH4pov1jGpTYsJ9I85A/JovbBLQAK2gD1l4RP7XJXBsr26JFZ/4NQxit2KycY+P0wRrB/5r/52qX
    username: AgAeTteCSh6O3anfVb4fX8ogMtLj1BAzQbk3aRy4KirIuddZF/w8YIg9U9RpV4oN30eCIE9sqQauXZZLVGqiPK07rqpGYEUumWN0h0hCWYl83ZQ1jU0dFYJWJcpbBFicGlNoLMiZRNl4NsvHfur+jvLB+VOoi6bhAF68H4WkpwgTEATMS6RIUmjdBPd64i6yvkykflf7j7QIUpfAKJXXANklptprzDn+LlprCP1DVEtJu1PZg1LeU2/dQ8szETPsax2fj5dUaTlsq/3Tt98QLwXt+fA4wgFTTqHBqHgmKfQ89ULz2obaLjQUEkFGbdWl2npMd2KR0P57F5oxAA3qKSfbKYVuu7ZJx3pU52Z62FiFV8L76eDuGc19406cgr+NZOXUb4oOzWK8L98kSTlign56L3Y1J9JCyU9wZD74D8329IiXOQ/SkEK73emYTMPKkhoXn2aDhNT5tdi+MVVvRrpsNRRO6Qe6oKtpU28nphNd7e38wb0+8Io2adHnpCRPoOFOT/aE1f2+1GpiyvXAZFqbMbH9oWSbxZnAwBoN330/46Ujn93lV2cXZ5s3a9xI09dScsw/VkAP0bfOoy4q9rVxZwxPGqkUt1HFmbs4nZBpA8CcN/HOyUPT4AKaWYeQgQ9aD9dthfsDtD3ZwLxHfrjrGWXUbTe4xTfywyItYb5Ll9O5F3eG6FXb+UHbyoVKB+pBs4pgwg==
  template:
    metadata:
      name: gitea-role-secret
      namespace: postgres
    type: kubernetes.io/basic-auth
