---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kromgo-gist
  namespace: monitoring
spec:
  encryptedData:
    GIST_ID: AgCjhzXpGB/icBCLlldSCST93Uw1XwHiKYTIC0duaPqhR+bK98x/funai4+sHZmqhq5oHJliysOayeAuVqlg+j5xAHblzNfzqzIINZG4NpwzDpidYZQk0UozqDNMvjKV52NH1WTMm7Th/+nHjhd/iVCcL2vc7N3a7w61ya0zwXXNnSXe8MyZLG6JB9JEcVswevTLvwigJqoiyN0GkF93lWYScNBHBcasfTmvqiRCUeF4RNX81PX27Lhf0GA+BCJxxFY/P06PJVczgySS7M3k8cEaxMVY12fHWOc7u3cZj9y36CE66Tw9UhEgdRM90/1Q/GicQ2DJUvtGNa5fI4+SBGoGIlINSQnU7aGotzH2tTmMWbTr0hqz0yMuHQThAknMI2t7+9lDasTK6AgpBaSH8CliPPThvBHen5VDhgrd/98JaoQcXz+ipp8gK7aT0J8Bmy8+gGi3/clVSKFQzigWo1A2AVr2rphkneFl2CLlZ15tW3uDRs/k1hDhxcWA04eddADwFFXv/JhbBNS9bNsIouwcLI+YjYYKEt2NJrBeNSOGGk6goVS9UuPqBKoHCaj3KawS+M1KQD7rzkB5lphqLIjvAS5Un/No+gwqEIMvqK0IzArh0RXu9CvCco4xh4dvLZlch+sdTzns9dXm+MmDAcMGAFT7jNKtmOd0r5HneqadS0d4ZO4gxAjvrdshmruQZMy6Ej/wt7AGUUb1qTq7sckQINoeS+D+41m8oX1M1U8lLw==
    GITHUB_TOKEN: AgCdh5yOaD33pfPAokgCuYJ9etL9ONNoHiYfpzAvT31f/YLxVYvpWHZxld8zWPivYYQHrlhVtdHGSuRzMy48fe0NlFc51JGJS983Ke6X2khoGHjE6dK1wn2+wIGewolKPuqFzAYlDLy4rKn9xJ5mmjPLxrnLNXNy0qQoUmXo2+NZ8tuPeJu8kpvr4BJiOun9/cYVjqYdBGWZEBARNhtZgejIYr0nkwREWeoDKEGHX5HhL1Zuk73+nxhGUNdkYfq2/AvZ0PydAYKuk/D6eDclAPIWn9F9i11JeDAGs1MW9BGt1svGbNm1AjTFVZCWfj3/w8BIqb/sMjGpDmGtB4/jkVOzCzeY9cw3Eu7CgF6d7a3+jSz0e7E2OseMrL3Z3/VBWqP5D8mkkrp3l7AYAbGsNjHJC9RNaW1pcp+y98pizh0P4919r41oasp0jCq5zayQM7guUdKLc04GST6nASSV4rzCMuR8khLlUBSQ6392f5O5GHIi3LkCpH/t3BqdbndTNFV6mfN/lU0vxYfgRSrWGRLB7NO/eUxdwlXLdmr9/9SjusEzmf/obIEywOWCrmYsU+3NEne8Z7ampXyyiVZaVZ3T2mFkOtlOqHHJ1n8Snk32eG3FUIgxpOZq8WVOgAubDt0mv+tVEmWXrwOZ+biCuvJpjdd44fp4g6qRp3yvlttUvDd807d57Oc276yLbwe8HYIJjCD16zvcKLdW6p/0CL6mJa9ZMous611FfXI2t53g5X7qRzR4HVuL
  template:
    metadata:
      name: kromgo-gist
      namespace: monitoring
    type: Opaque
