---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homebox
  namespace: homebox
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "3.7.3"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  timeout: 15m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      app:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/sysadminsmedia/homebox
              tag: "0.25.0"
            env:
              TZ: Europe/Brussels
              HBOX_MODE: production
              HBOX_STORAGE_DATA: /data
              HBOX_LOG_LEVEL: info
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 7745
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes
            resources:
              requests:
                memory: 64Mi
                cpu: 10m
              limits:
                memory: 256Mi

    service:
      app:
        controller: app
        ports:
          http:
            port: 7745

    persistence:
      data:
        existingClaim: homebox-data
        globalMounts:
          - path: /data
