---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-data
  namespace: homebox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
