---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homebox-secret
  namespace: homebox
spec:
  encryptedData:
    HBOX_AUTH_API_KEY_PEPPER: AgDI6WO4y/cPpIo1F1sN3Vk5ZoYmTa7ezxfTOpxC936ckbWH/oVmZKS8EV34X0E/6kW/Rki07y77OfrlCYzFwiHgK0app03hIQZgst/dSgiMtJxwxy9xDpLS7iU9o9aS7cvcMQawvLW42SVSYSc3QFR2OHGrOtyNMF6Ar0j74KdIfJpWVXCsI4Ya6WsvGD7bNCahjOSfziw5Ctimb7nw4fY3nIFeqAYLCFRxYx6JHt40nXpz9aejmNSRfi00NpZ5fgNkyIIw3QHcuRldew1px0+9tx02b/OmFzcbcxDoD41rnJbFcCdnPBoK9uDaBVICGosq44CnobK7ZZdtz4gRl4sR5hDnr9YRyBo32fEr7kzyXREXRuJhmffv6mjlrRDwKg42k/ipbgq3LSONBLPqIFImeklYICihWyTplBRiCPR1LhiMguEgNlyHj2mtXp2uc+c1JUTfKswaATayEM6wRCXndat5EEKMAjZMt5w5wfJI4ebjVxnlLANobTaBeN6Ayu7LWq/eXCkntpWy0muz2JvmUtNOW6OGnL3JY2ISEvCcrW1WDKS199YrHCT9g8pHzb/YCx+AXbqWZD0/JoGv0CohhKwpHK3dqb169IBKXVIgXuoK0Y3EBiFpbC9Hp+QHY2xlzIZeX/2ATGCR46vSiPukDUCYpC3fQZ6t6pHQUZhJGqVEq4fGkhzr1tnZgueJrdfeTaWYdeIjMqkokIM2za7UfXHFdULe3m8nk5WKcuI1UR3NJCBhpKa97NSl4pHtV6A+G8cLKfC1uMJL28Pciq4B
  template:
    metadata:
      name: homebox-secret
      namespace: homebox
