---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./rbac.yml
  - ./databases.yml
  - ./script-configmap.yml
  - ./cronjob.yml
  - ./restic-sealed.yml
  - ./rclone-sealed.yml
  - ./gotify-sealed.yml
