---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rclone-secret
  namespace: postgres
spec:
  encryptedData:
    rclone.conf: AgCpUmRIRS+zoCHEA3ADakAjH2qJBFFU5ryiGcJeZeNHvPIvWmUob9x36sRxWUIqozZlMzbioM28DKfQ+d15WG6Ay64JvWt5gXJI7TFTb9JX95HAylX1i4LpeLPIuAW1MVC2sGwrbhFO1IX/sStpQUGKntPvWvrvfEqKH42KnI+cZ6VAnZzaY3MPQjKmrsUwdJlZrhZ1k7G/9XrM/u7MxVpWtHSb27sD5yz25GCghx2rb2Q+CFVKJAvdb+U0ntM8oh5M18He9nNXYOEQSxcxEk3uiTGCXfG9CWfjWGlxnJiUFOzfHUfrZSofTlJ7vJwDwFmc2hmHR6IruNbOFVsdJpJlSQrcjRusNErhm2GKmLsNDk2WlPez00Rx4Yl7MF7EAg/vsMGdeirGoPUQdRcgT4obJNW4cieGg/AElj7QOPXvnaqIMWJZufJMv68qQWabKQIyBYKjCO/tU3l1vUqZqZkNxy2x2uOyLbJlplPRtEVRJoyUl7hJO7Og0GeDoUkSOe+V09987R/J/TlUrcFiju2HoTCnJO2W7qbx/2qgPTDnJ0dzGDb8JWeApDxnPyTA+lltJ1GCjzRP5kszD4ybnj4u0LVLLD4vD03zNlj+LLVy44q+z1Q5p/e8WCfz5AqzgVj5JywteQTsl4p2bTsqyVEkhXYKMBXwCrXDVOo8GP/86pbRj8FpnkctUe/l3AxA6ZGzWVPZBXTggfv3wuGgJ1VSBBXBNJ0vsQWB2QpRQwGgI3GrCvPspwhHjxRG2owRMgp2V8MyPY7XQgKH6l/3sSsCVnmZZ/gTkRAR48lHoWNFv+7OeDgDxkVqqeABMjWx3hglFlEQH/is17q//t8Ga+LLySL+ySQTKj9ZGGSZYnqQQnBCx9LbAYUXuWl5LF3AH0KqTFfn9PiQ0XHlcFepThOGjGCQ63arfAzofbVP/G2MMTn5CT/niFWa+936bspZ8pCNyVbThg3x/brY6lbqlzOIf9K/gebMbZrU5bO1QSC7LUGDB+kU+sDk1nGsaoF896GrnmTht1FNvU8vgYFFWP02ZrnN4lq1Edl8fPmhn/adyB+AtNk3mC9h/j25KbpBiB3ykrw+5KFE1aXN8PwQgU5vCCzI4kdW93BDd3URio0ko/L0W+bCbtyaU6c7naCVdwpV5CY4yTEXFRtkKAu+a2uhmYLidXGpbSOBWFkzjw6rmu108WbJYSW+9AXIFIU+pKQ/Mn21MLDB+75VOm9y0KzJQzsIAadu+6JYmNQirZ+2AUaBl6N+UIZfwrVk3kUsQVz+fHGaRkTtkzKE+DnzIUivhhO3mDxSdzZ89uh0ARIaT8ZaCyLAU/BX64Luc0tL1zrYcgPk9hfjmd0e3SVLcpsKqOv/Kn6S6wLIFueeb/GKNX+V9u3++L5AUFtXCfeB3wWnYOVHIGycda5rh6vk3uvBumB7F3gqyBWIYRbXhfa5yarHjv5rpv+K3mpS7B8JIqyt3vtQpZqV2Y+BonF+ABSg9rhQH/cAaGbAMEibapgzg0WqKbF62J3mtJJVsTI=
  template:
    metadata:
      name: rclone-secret
      namespace: postgres
    type: Opaque
