---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: postgres
spec:
  encryptedData:
    RESTIC_PASSWORD: AgAnWTBtBhe7K44HCsJ7qggsoqPzZcUN6fBxlY8FB1ouS6yB1r4tuAtIrbqtEWLtBg9CttkpCxVmM07oP3x8Jdd7QgfvQBhzQhBrPS1MzcoMlCLPoLcjb7r2OJENi45JVWg8dbmG8GBx3VUC3yl8mNw0s0eKFmgwmrHOdihmOOkhYPjRC1npoiko/F9UnS7+kIF97OhbIOLu1QOSwBVWLf1A1dPQINYXYREb+7tLSY0Oafa5xdWjT9OKhCqjAGapTdsp1CHIB3WfNJjKR55pmZ32AVW2hpGyLA0LC1OSIATynJBNqV+6nzoFmCtnG5JT0NS9LCji5tZfJSheriIcgZ35ejsKXdNh5jlq2eSe72e2zvyRUN+Ru30YT4YJ+ZHA4vJ8HHxnrDOvZYs++38COm1kYXf8fg8odLqlXpLs99TdpfgUnTwKpdJhj91BAy9AbC00J2o6AH+/J6mYFNw2lmMdbTm+ij82VPhaxAbJqAw+tUrFItaaP60C/dtfpxsbw9sd8tD5kWEztrDu6CvkRJogh/47+1RB94FoG8sFQMiRFR09JT9i/AV6S/A+QxQCCLe4wX1dm+r5it+3O1Pwwt1WaJRmq/UKr+zMTMZgcGNM8+qM4TqxCD+RvCruJSzn6FS3/Qpw2pRi9MobIW2G+0W2nfCgl0ofN8ZDaqhAYVZjigLyU3CtRJHRm2fP7ZN3/15phFPncIsof+72cMiiCQCEioj+xYuPO9BN3lK5gQ==
    RESTIC_REPOSITORY: AgDGid7NFx2aDVI+Q1xd0lQjTDsFev2AG0SGdQTBaabUuslzstj9vCob9Rqv5RiLOaUzja4BT7MXDtklajm3F4WTfUVdZ6ApdHEKadZ6/maJlW6FsZFoaEMq7eJFXJTcWAeA+pis4wyThEglQ5hwx2cXl7diadZVQsJH9zOx/Lyw1Te//nIyt+CcP5NILpTL0MFG5jKRoBl1IurDILUa8R/vRij1A5cpeYONvRl7qU33d99PqoYswru5WStl5GW1kRe0bFJCvL3dxrS/CXNUhVv/DovC84Rx3dQXAvqTkAk3t8Xho9WiusF1B64EOIH5A132EYciWgBmJ+cBS0XkzQDuFnoQdWq2Xm0xCvD3GqFHlc3aFCD9V8nkqIyqeaRGBdNjYdn8ut0gaBlbrXjkX8MCtC4iDLBLh928PbBukt0OMy9sqd3+KBV+Ns73JyncesyyoyK0lVVD3TqgHkyfhQRWxYETtkM2nEZ1PqfYnIBnHgwykypLyFuit2t3zeRBboUS94PybAJUoxUXjwBm/MNluHVQ2LanHmLcTtPvNI1xpv+nxoz0W5d/zcNaDeFnWL0pOisZmzpHXlUrzQQwnme8NVPvWAKyOUcOdHTMFF68kvRbL3ElSTpgaQWztTWQCOHrcUMfBqrNXPm00fLwfC31g6GLaa8RrN5yC8gkPf7WVWdL7dssTVXzRw356ZMWZ/SpJRfHq+gnixNljGEqBktbgNxjiaC1Pd4kte4Gn8VVUww8
  template:
    metadata:
      name: restic-secret
      namespace: postgres
    type: Opaque
