---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: postgres
spec:
  encryptedData:
    RESTIC_PASSWORD: AgB5eOwlLYoGEpU0kxjZpxhLxN0ZXaeZ+sgNoMn3LUS8ITg+Gx5d+OSM92Nz3N0cqF/kbuEbYz6g/bDPduhsA4cXg8ybu+d1AxZO/Cl64+E7R8ztTLdML/xymXVJByFMTHlip+WhYEPJ8dxADqXVeLvpTRnrvEGvqCnVL7hGeum0/mksmb5kXfsgGwNuEGMfgpiur+1f1x2hIEEJHDpq4UvnbN7oDA/98aZ/eGhsx7l9+cYIlYlKy9sLVQaERmdJjw8NkyXpkjHfCIJ94vGwiHijkU6Z6sg+CmeNpsiGKY1zKJYFqoZXb0aSsE/Yfo7ycYPpsfjkYXaPXsyIG10s8Z3eoWJsnw5LqxaDdULtBa84xc7NDSecadB9tOSZFUiRSLGR6Ggv97tSQfW6LEYfm8MdbNNYKlrC7Gv14ARrVg8ZSykGFvEVC3DDAPpzTL5FcLYftx1h1dY8bRweqXmnJyIPkHiZc4Og+tHQlPVRD5qR+RvC6CzWQmGtArfcaeoOjzCA4A9L8OMrsVdA1birvqGNiR37LmgU//gQQY6QB9eSo0reXkA3P7pcORLNk9QOxLBt8bgs7ZpAwLqs9mourvoWTa3zG0mui+kysewT6ubZ/Xocmgq9jRjt2L5yyvAaMlhfXrNeYYJReJ0nS4LUKGB0ySOUtObfm1NfexADd0iz9Nq6dbVWY8bp/ghR4Ktx0pi0aBEN+nrqd/5LJg4M/1rtZFsK6Ypxh0afJrk1HfApnCM=
    RESTIC_REPOSITORY: AgCEoekdUsJejbvbeFEe55UwSEA1xQT3+1sAJPh0LjDF2QeMUpPJZCNpq5z8DV86stwLRalgzENJR9904bKv+2N5xg8HynNwzZulXBQHmvKapd8uORI7qAWxTvhZhM7iY69UXJAbVtKvDqf+LRa/kctLhmEyNHxHxjxgfZP7m2dq436y8PoNk7XnOJQPVi7nayb4JniYbWvjhOuK9dhrfmrE5tQThft6rLwGakEiSiqgIdjhjiNTGDg9Lw8/MIaHyeFuYmUJturBHh9Ew5wvp2Hbd6gUn9Vg6LUSQxN2RVc6JezxIgJq9sh63MgkhuXPpKVpuGOvG1enciXwp4AgSI+7qfvoK5EYdu+k4o1IzkAK+BhnGcjS+w9NAcJiFmPISz0RWG+T1tCn6hMT9AyE3D2y/vNExSLCW+D00uDT/RPvuWACTQT4pcowoYfMcvPP7wLzy047jkAOPXUxVnYDuykR47J9BgGkkBAZOoaZupwYnamMzlHL12Sx7f+ah+VU1wB4FNOF+GR7Y8BoZjoFtzfDMRjVo+B9WQZjThUvJlNRFS0t9wglW78B5l9wSHr5D67panjPGqmhYfyq4zKWP4ynfYWXOmagPfib1GCL1fogaJ2ifcbhADccGY8FP9HZke4eK67U6mGS5f35LnBumIhjrI+xNW7kW8XvOgYY14BCMNmNtSwJ9k0VCleLNqIRbW+B5oqd8TZ6D/Ha9TZ+KLVs425lp3a0thOL6Zdm
  template:
    metadata:
      name: restic-secret
      namespace: postgres
    type: Opaque
