---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: postgres
spec:
  encryptedData:
    RESTIC_PASSWORD: AgBr52EIWt5S8v2eOU3mvoU/XWTapKEQfUFtBdHDa3tofL/C76VUhRMzipLy6ZozaISvihdpnvtshL62Jd2J3hrrsHjB5OKCcQ/DgtpkLX2EHoAgv6NbQ4OmJRlO2+ZrTNW09naPy7r8lbwz24AvflAkH2rPyC6n5dSVBlFqtaO32psSqsdMPMDH9T5WlYdxGtCWVl7orpdkp05z87/LW+94iO6sJW50gHhEfEbF1zZpwVVnzKNe8LBKK8Gdyvj/VdW4FPSTZtJpo2hIV95kTizw+JBApU6QyqwT8ULWxTAH7Fl7yag3dVV/Xr0IEtuwPsEhWb9IWmIa7TA0xhx51g+78Dr7BUZpBP7AOekRIaasfMGvUmB8HWgk3lzKsKXEP1Jo81FA547yjd47ldDeFgn2hRZlOgJT4/4N6NpscdUWumIJWxQvNjdC1apinIU/D49GwVJWMUtelB2Q0uXI5oK00C4KyLf06ZE4pySP7+E0pEF/X/gmrkM8ZL7FB2M9vKDQL5Wqpjjy/GIdaWg99Ld2Rrso9whl4M6GwMyLzmb/aUs6T3/nMFEXaTm8VQS65a82Cc2ul8Fcfhnvn2SeriGkJxtSF4FY3JwIQ0XEkEqzv92ZZW9Hs9rGTPZ5bi6bM9bBJFKLE+qwrMNEUYHNN0RxzjRdZTpAvcBxTx8lnx4A9pjXXZmBm+x5ifoXWYv/AWgpz548x0mKJcYIEoUtNY41mUSyGcYbAMffbqENRwVmFGY=
    RESTIC_REPOSITORY: AgAPZr3Bm370wAMobSMwxeHG9CKzpCUWjZqYMPxBKV8qvvuoVtYIoxm70UfFxSdi3aHsEHC0Vtwd/Voea13rMBgQXeixYRDu/t11Y4corREed4TNeaDl1iEGCNfHDqnGWR+KgTSQGI79b0oTauy4vS343Sj3jUkuGsDAxFJ1IfuNDiQ9ymM3FT9THodsWNt1PS8Zv+gv1UZudPjBs2XKjXV7WaUJCJsj8de2tXZR+yhJg6KjAUU5l8Gc5AWeViI1fGjXQP0nak+olctZI8AonIULtxR2FezuaX0D9EaIdkBeqEmfgTbmid2qRoDFGPcyJVQClGHvVi/FTrd3y9J83Qt81+SfFhjCbUllAP2g5o3DtdtWhBAhfJgBFUwyAWHRBXZEUg7Ra0ClJdfIADDmYeuZogSu85eTMDlYiMhKLRR1jMxmMyqV/EJDUTBr/f9gmkGya82Z1i+R+1PaqueNuWHkAlDMSY+S084ob8pQC3ezhofVTDFQjnlSjsYCe3Q9ztExZlyXF25t02LrX77YPHd5wUPUkGYDAJJ1oGITv/zn7gNHAzlWg53+1daX8RvpD5ciiBX7e8pMumYYY6JmbpPoQixTgHwTcKd0AcJnHgA1jEhlAiEJOaqEcFAuOfBTK1iAhXem4ExlytFmEEhdCA7z6SSMTrgHbWJtadSyeYc7DVa4AAqfeUxjJYX1mu9UHs8wCMEwZpSmH8X6yRigNX1Wam2kJVtp854fsi5QGIf8qx3leZc=
  template:
    metadata:
      name: restic-secret
      namespace: postgres
    type: Opaque
