---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  encryptedData:
    SECRET_CLOUDFLARE_API_TOKEN: AgAfAXiSI991+Lx1oZYBM7krFpL/BGb8rzGOdusUSMErrs5ZBgao67xk5uPaXxOOGXGhiHml8isMEXWPMr8FMO58EllZdfEl071xX77ESFTXKC9cuFQZOqDV2JtLzZHaEtwjADSxwDUaS4PIraq77XPKJL/WmUIFL53CZW5oIfpqQ3NCig5wbysshslXQnxK/v81yYbRuTDJYvbGJ9eHfOj36pR31vpMvAi+AxcB2HXm2aWwo0U7jeai1tYbws2ujVf+u0Adhs7CL1PA6HkFBRGptQ4bPwjuFfrqymAt1Bpmca6B68t4bw145F4Jaxh2Tn3qCduK7h/Ne37UaNpS0UJrgYfbeYcGBc0PRWEDwjXY93m/2eTD54zqQDcMQ6Xr+0hSZXZoZVbTbTpD5V/JLjU2qQ9v4k5HdcCBKFKFJb9SzyaZHO3XAbcMuyhL8AT711iSIrYKteEyrmlyfvN9f5tG0qUz4DDGfWtu/QgF96ISOnBehlr62BX73TMRkW8x19cHh4zCbb2qHMFX9A59uSXJYg+UKUDsftz/wqwcl2FDgFYaQNITO+l6lxryDfWpCLzF5EJxfu8yliVRLsZxoSOYUHzRrq4Y4WIdjJj1ffK1Z8LcF97zfxnyL6JMRwNTIssqd2cBhf0FcEzwxDb3Wb2G1v5WwYlYV+GMXqu3674FP46/X8S19VGRaDyFEnh3C2OJ0ERuLoj9hRFQHpwxJOBFMQNQSt1gYKocPAQL3aCOSf6Wuoe6TJTY
    SECRET_CLOUDFLARE_EMAIL: AgCRcyNUzY+0LbOnXGNV4GwOvWu96heno7630To2/YTTfkL1KGanFjv1e/29UILookeKR6tYaS6BrXeX5jVmY5gDmGS/buyAK418PfYM+q4vmA128pTOI0z0Rqx98Y5PIYSf+MFvQeC7MO0oZ6VkwO1RQ2jrY9EOVg5raxfzWfN9DJzf+Vr6YwWRhmI8VKEi0nVYUnK1FR4kWgCn4pyvtTg44fJYV++Cg6LL5HFjXyjSj/DFaJpogJwa6SYndvnoy02RHzpmUzrjiWtJgAu4EWCcKQbNp6puHTh1s+XBuumkmR69Emki1onS899XpQl6hcc5V9WY3AmjHHyrwYgE+Oti/YkSQZc3T+XgCrW7ggl4xUe2U0s+id0Jrkt+obuba26i+5VO0Guc5N7viS9dUKHvbDFDfCWG/FEgkotVBuHnfb/Son2hlZcIQD76FXp4dCZtEf5hlyLPd2GxHl20aGhL4xIUYXy6Q6sKE9cQFX5nc/aCMn80nlg2CsY1cd5c/Mu/RbDT9MKtxHPPjzH13bfJdsvtc4ZsLc8h/btbEchNpiMLx82CKpY4Dcvsirq40Oy14mrd7iyXLtd1bs7SlIedw7Q4TUk9eWLMXrFAO7zIkGV9h8BZO2eA7wWh4kxBswXgPGn/AW0sK3V35T6rLZFTa3Ibwhz9jNihJXqf53eeuGIostdomcX8ShMyyYCBQYjsqAuFCQSCDJXnp/HJc739WKo=
  template:
    metadata:
      name: cluster-secrets
      namespace: flux-system
