---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-role-secret
  namespace: postgres
spec:
  encryptedData:
    password: AgBuf5lo32y1ho3NUsX6i0DXHdv8Zfb8yNpajyb07/4GJfuQbRbTdMfuGEwnWXwmrs3cAb8AHJrA//zLPA5leGWaLi+Wtdvvu7oPn7upnJi6ZM9F4DX1MZ8LJdSyVAKWHDuAb3kempz/imw1OS1XZAjrKCqOxEbaBlToNeq/P7NHoO2Dkt9aM4Du6Tr41gIJFWnw7sNQLufilTQFWwi9nJRF3WGAM0Nx659gEMc3dIiZGQJ16SFilEzZC0iiVkGF9QwdzjeEh3KYEMDyaQJ70T+pX7VkTqirDmYcfhcM5hSVe4nOcuGpk6D1EEHpAjnipdgDtNhc2EedaSHoMCf/jTbUmAW8LF8jSTXRT2PgrM1NBK9fZWz2cCfGLjSJ8AdnS8oQJ4TYAOKYm6ZDLUvFiETiNWaIYZZuuWQ8Z64j/6jS7coziqy0K0AhBopz6/C5b50ML76b6pKc9QpqehghBzwXPFScg+B8oVEsmcP4UmzFYyTXyNLxswo6z2A43oS3+FTgLRN7TtmFSiYHArXsG298x/bFav2bxW/bbDgwTn6b2u/Q1AXSbrqsLGYZZkmOYynhA9ioKrJeCi/dJ5Lvp8lug1RRNjgrEia8KS8HLCj4evnu6My4nftHkoibA3rSGliFwzCH2AH46cfNOFQtJE2mrQ7fW7nve1fClmx7rScCqYxm+JV/1Rss60jqLh19hXEqgZhhtetKu6R1Y+GxCjcRn54GQI2jhjk=
    username: AgBaQshYAYBSEMoz/EMWnQtL6DE3/G1lPZwu+Kmw4IvsvX9LDriD4EweqlU4KVm4LrUyp3QyGxsm9LTJha9Wk3GPST8OoIbyPTgAaXoy9gBvxK3ads2a1MGg+3+3Okzp27gJIW8FERoHAtpLJDTFDhpp2UpD+/ycgnue02QrSUU3dAkcLiWhFxnbvtgtMOguTXQ4af5LIigPSGLXiHfXcbHHwkyPXU4AX+VvRtiMzkPqg4FsmYyAirTULdwcvL2c4qq6jyAbrb7uMOxGWxnEumAanxTMXaAVDn5XwmKJAdnXPFl8WjRjy5S2i6rmSu0ZrauwjltCok47gzzsS2/GFfSkgUuP9kxFnCtTOdVnWzXOfaV6WH2CFicyMepFGiWsiwn3EaeDpat27c3/Q4lCmfx8o/FMApzd1tt6uWjrbOG6C3YaTI7MRz2guFObiM+vhlbOeLA231B/IlMblZGBMOgXy9q/f+ROcUf1nNXRIjy8ynfiuGvu12xvmUgpCaP/SE+Znjcu45y8m44WCFWhmolrzWLZffRwL89DeugcxybuBfu2UWFvkGXGSoWkaKQTz3OQXB7Vfu5RC2CMNTxavlLqyllLkVSsBFbOdSZxJWmKOMz/jWqFAr0Jqy7uq53uvKfMuBDdXF7PwTDjDaX9PC5WTy3yS28BH/4BgfU5pOuejzs6pa5QzCLdI0blpkvh7mg8kMmV31w=
  template:
    metadata:
      name: sonarr-role-secret
      namespace: postgres
    type: kubernetes.io/basic-auth
