---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tranga-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
