---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-pg-user
  namespace: immich
spec:
  encryptedData:
    password: AgCNgqZZ+MOBWm4z7HDEWnH9aW9sl1wkwyhRRpEybXhJpiM/zuZWS34stqf1f0boXZfoHQTJK+Ni6cUTJpb5/q6QyHHXLDv/UDm7wg+doNhMBDQEljSCzUorQZnxinB9Ph+NTHdGCYcfjBGy0USzXpOLwzXdh7OHB4BgVxADROsvJvUj0hMqMe7PbEzEnM8j0FdNRRRjXw/egRBdD6YAzkZMIMNguNb39XS2+iWxxEwecGb6T/De30svgw242e6veVDxeY59EZhbfw01eNslVoJRenti+cfVv5QY94ABzO75StfOG0UtiVaBkRiHpgqJ7A3MmiL9/GNEuRzqkPxAMB7owVzNPuDMjpjfREB6OCHrroDIZpKdWx1iu381F8r1/LDxe6rPIzY7CAJ7evqK0kkyf96+SS2BA9ZO7d4ICSCFWcWo/f34mbJtpTweeXzxT4SKolFTTUVvOXEZx7zShhURPAQYpMQT2jk0SnDPgEtkX8AnI/K0Y+td9Vo0PbKGkmbJlTRfG3TzBEFJA3v2u0MsQCpkHZESY0YQHtH15ZtOB53QEjXNUh6GXuVif4yg4t0CmBQ6fLqEPohmQpKKfa0R48UlSc01nX1xFokEsoR4ReL9D++g3orZoQKTSel4NArsZlrm3sZM6KYDbHgxqUAsNuA+exeO5o7pq0xiSmC5p50evkuaohqmxmeoLIyECmEVXMndfg5qBzpp5lGMDz8q0hCrpDSi+hR58f6h
    username: AgAsqAkIRRrK9SY24PALUtfvv6452acIxS4zAcI/cOgJGh99EfDVAQJm/Fh+jd1C70lcTNVDbiUucCmgRTfXjSiPfcFOfkDO7la0oWrZ1zIgyt0siw6oHXqy8ePf8U1EFQ+fjUyxsPaKSme1+MJYujkChf4nHLkghyzYyMhuWQkCnEdWEhstKXDMyOovLvvgt0tZ+S5F6Ph+/4DkCaacYD3SfSbPhWa4yxzTiCFAhv4mFaJgzrtYEsref/4kIzlW0SYmVY88R2ic07QZTm4aK3u0HM5zPNADRFChp11ZxcGqIVscx5+P/quQ+Fom012sj745iBKuOkrQvRLrUZZUEzrjmkqT1sVQjGHLiSxcUQj1HDEc27aXY1jNaXTav8srPUGTLu/3B/UasY5qfqjNn1svSLo2h5N3HHTnugeYiPw1/mwfAeK9KKmUEdvpe1r8p6Udi/3BbIhbkMl7M9K5WC4RU8ctPqamney1D+OwjkWRAeflqa6L4Hl7N9Mxq65Unf+Ha/LutUBWI6BLqBxh+Zi2eXNQU03PCl0bz9M9fEdZKeFzgS7jVABOtzZYoCF8iXgO1iCpLVTRwjMwGz2j9dxM3Xu61vnizb6D32ap/kfQAd5RT8klRJ2xhCCS2BwDPNpRhXzxYyGurEBsZvIx/EGrUQ5tvfUjVPWQclPFYp35w6jegJqq3Rg5CAQumGc4K8TrhBX7Jrs=
  template:
    metadata:
      name: immich-pg-user
      namespace: immich
