---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-igdb-secret
  namespace: media
spec:
  encryptedData:
    IGDB_CLIENT_ID: AgDCb1JkfHOs/dimzEs3sqwFu2+GdOnP0tiM0Gj58g+L76DGZ9AgIOKQl+gl5DQInnXFIjoelGA2QfwZt0MggY+Pe6ZdZb+M1vDn30Gm0jjKyOPYH+baNOzT+h0CFgVbhH+rSAplR9uPWKQYis51sU5nriNL7K51KGeAxpYg90LwN6PCE4+our97RbvcdDgk34KX59DmNnlTDADLegCjYP63v0S2xwoxcjW/+SxtxH/kPsNA839R+q++N2HfGyFLifztDUZ2qz3P9cbt13nIounbnJuqbdrJdnzPZT5jCqA6ZOu9AjvppEuJV/SHJw88PxgkqHEri3vM+Y6EhECcboHzpKgYASRV6AZdWwln7yXCPAbhyCsQen8iKuk+9eR3FRqsJR96IrrSmdieSk5Vh8D+A1B6pSIN95t1Qb8OrFOqGlvzCRFuRnWpyX1wT3/r1X4OVXPzeJitmxjuxRvbS0UURHhD/nlEXj4fs/E4cjw7WSwXb4wFjwdmmep0aNv24Gqvr5fjpiiavC4o2dNsNUhfI+Ajq+YmJmFRFmg1H4rbWwd9KTgxcto2El/vKYbIOh8cceeH5qkuHRTRU1gnQ2mBmkbX/3BXMsRWcqzISs7XERHaL/x1ZcL2DJnSsMN92lPwXbqGWcblH8URmxJ9jiCDCepJAX8TgIiOFDnRwd4tnygij/rGDE0y6eOxjlhx54xwnRwXIngRB4O7owuDdk2ak8HRagO5EBTTdSsguiU=
    IGDB_CLIENT_SECRET: AgAnADing7bDVS3p7x4KK+FHvizkYENSopaddojr9ehuxNLVbNvj+cB6XkOGcf4oHcjPu8JmckwSs1xDjZElRkh5vR9aMybhx1rZAb8B/0k9nhm7G+QStuIR6TaCVincWDebSUiqetrouRURZT1Pj1yc8SfcP0d87vxxseqrBJFAkNAUjmN3nCZapf02gXUZIwiU0rZASIekXzmnSFJCwNcLGxQxVCyMy4aEY4dEjJjykFkFhOEzAFZwMBORf4kV2w+M4vm2jYypDptIlLppLCPKjwuQhZjEjx1o5T+jMiuPKfM9pgHLLiXQO32GoHVIi4ys013g0TBWHXAglAGogA6GTyIk6fO1fXFGfeCLc1+uR7b4mvHhj0WtyxBel/ebDht4+jWMX61Am8XMEPuACuVQfmbh4b1hQCdzHy2+XErFMJPQHez/53n8AzlcgNklvW00lXAOquF72q7UTMufl0pf7dNp1s80B+YZ8ZirmTkrCnQMUVC7tLDlUJD2PwoCmBKkWkiIqOxVrYeD3qrj8wadu+c2KsZqFAOzr6MFslsU0KBKoG26hmXZFNhy6GeD1/cV8VXeTY1jp6rAKk0+bH1khqYfNYX5zOJMyObLZeOpj9HEMuF5smrYvAMYLadppq3J0riIftOXDTO+iPUqIvgdnKV2tRI59w56VPkHpk5co9OJy63xzgEFCtrgQW/x3k50unm+YXkLFXByYVbIC5cNwN1VrxLsqLh1casrLeI=
  template:
    metadata:
      name: romm-igdb-secret
      namespace: media
