---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-secret
  namespace: media
spec:
  encryptedData:
    ROMM_AUTH_SECRET_KEY: AgCc5nNGnqqs2pLJmKVgCTB28Ob7cNF2W86HSPZjkdg++5rkE4iJCmLsB+QZiYs3eqat7J9LITVvFJ00Q7Guac6AhP//7sT49lSA0206E6lsiYih0z4M4E/OrL/4sgW3Y7T9zh+2+L44S9458aIt2dq60o10M6iUYl7Q8w52NyiAuprypjRrvFCxb6b4sJi1OPqylbtbXqU+CbZxC0VULWGxFYL+eOqlYlSdcw1mdduAmvj5IAY4yU5gVXKS8bG0uoy6pdGmdNP2PockLpEZqH9OD8XNbVmq4p8v6+NdB49gHJjQPThLf+RC3myvq5MfHnIkXYteC0K/6fUMvDtE3Z+NWYlwJNzVlkjuqjRBTt+DVOAXAK0LJHhrPwuTiOV7TcB0e5x1jtT3cHMaXuGyRux4q5nHYHAI7Eau0a1xXyvStD691nuN9Bat/6aPCzxW/bCyRxN6W4TCHuAMRLeTui3gtf1u1rANg5gxvNMcExiOjOx3Ip++p5KMBCZ093SnyV37t9IMQW91q7oIkc7xZUGyPJT2X6J86drOeeDwfQT8K3B3rye3zB2G+s+PSP8jrd8L75VdkVJflltb/lwg+taCKsHSkPKzWdYBxWaXkwdHwoiYEwl3r0mi6Yty2WODtZwGALOuZowEOnLgUbLDQ9qaUQy68h5w+CfPlQFDOxWlBc11HhBb+WFV8Wnv245YmY94zOohNj+AC0Wu/JMNdemUiqhYKFTIBE7FHHjPMpCYnQzWse5C0cJSmq/DNtkpxGjqR0XJ/gTnk1Jbc9kFjDjG
  template:
    metadata:
      name: romm-secret
      namespace: media
    type: Opaque
