---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 2
  enableSuperuserAccess: true
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgres-cnpg-immich
    major: 17

  bootstrap:
    initdb:
      database: app
      owner: app

  postgresql:
    shared_preload_libraries:
      - vectors.so
      - vchord.so
    parameters:
      max_connections: "200"

  managed:
    roles:
      - name: immich
        login: true
        inherit: true
        passwordSecret:
          name: immich-role-secret
      - name: zitadel
        login: true
        inherit: true
        createrole: true
        createdb: true
        passwordSecret:
          name: zitadel-role-secret
      - name: freshrss
        login: true
        inherit: true
        passwordSecret:
          name: freshrss-role-secret
      - name: paperless
        login: true
        inherit: true
        passwordSecret:
          name: paperless-role-secret
      - name: gitea
        login: true
        inherit: true
        passwordSecret:
          name: gitea-role-secret
      - name: radarr
        login: true
        inherit: true
        passwordSecret:
          name: radarr-role-secret
      - name: sonarr
        login: true
        inherit: true
        passwordSecret:
          name: sonarr-role-secret

  storage:
    size: 20Gi
    storageClass: nfs-client
