---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgres-cnpg-immich
    major: 17

  bootstrap:
    initdb:
      database: app
      owner: app

  postgresql:
    shared_preload_libraries:
      - vchord.so
    parameters:
      max_connections: "200"

  storage:
    size: 20Gi
    storageClass: nfs-client
