---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 2
  imageName: ghcr.io/lucid-void/postgres-cnpg-immich:v1.0.0

  bootstrap:
    initdb:
      database: app
      owner: app

  postgresql:
    shared_preload_libraries:
      - vchord.so
    parameters:
      max_connections: "200"

  storage:
    size: 20Gi
    storageClass: nfs-client
