---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zitadel-helm-values
  namespace: auth
spec:
  encryptedData:
    values.yaml: AgBgVsUmKBlNrvLI5N+Ygeu3KYD1Q6+N/HOfha/JvS65oMMbhlgAOKCqovtEG0XzQal5y5KJjshHrA12HGaKVBNp0mVQNCP6F2zMoh2fLSsIi79vZpMJgXIV5OMNEBBCwat2I3WAEbkKyUhepNCLao055fgt0r57FtoHoqCSVijxY0B/meOMlCvU7UAJa4wO2+TxUz2oUJiOOvqjQkqmHq60Xv/IKe3PwmsHfjMfYqBfRQ/kLtXV66YQVTuFoVgeGYFGJ6GErlZ9xTCUKKDL4i3vKqQqx9iRGOjltiYBTf5B33v2WvNsR5bIEGu6d+Ijn+EhH2HSZQaWV4gD2fNQs4+kPNUTVRjFvl/CD6L14akABrkr+STHSd1KwX/HGShABILnduyOHKIk4HGfOqGBhL1CYccVDVfXn/jFktBj65M/vwb7uCTNW007q6FLYwAX2QiDjWs6vtO0bw1y0DSj5RyZBDH0osMQP8BiaLesaOBO0VdGebhjiqj20jTH5oRtCLKNIE2/GYxDhiduqbCWr503pLsWXOWiUtI9TyuRfa+skKMLbXyPiGgSoBk7y93DG7O8UBeOA0bvuov4IaLtSX/m6Y5DSp+BST5YgHqkCRkwc60u10IcCfUvWCDssvp5YyroopNMaz77fY/C+dQcUM1ViGZkbsR7wiWE+rooP/ULrdrUYariU1Sc/rUcCxov8u992djsIgMQD+9uWYpd8xob2U/u6UcJQFu1OSjhK4pMp4AcskU4dTQJ4GB2W8OWZxxW63uI19n2jSbo46JDUL6FRxcgJ38JshgAy/k1fClogYUjxZ4T5kjuCiXc+nxX
  template:
    metadata:
      name: zitadel-helm-values
      namespace: auth
    type: Opaque
