---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitea-client-secret
  namespace: keycloak
spec:
  encryptedData:
    secret: AgC4lQ26BctcSi53pJoxqDmnuckCHY0eTA380GerCCQ0/5UJQeAJH8EvnIwgoK7Wt4ObSk/LtVQJc060LKG+o8PGXoq4pZ1Df7PNot6F4rVijBxhYg+5sWmDT6UbDHyH13s0PzkuHQfqZkL7ZJT8A/PtEyjVQqGPf+NMXrbTFzOdSRPiYJdyQi19uzSiVIsEQh6U5ZOT7WUybjG667Y+0uoOAvXUzQZgBWK8pF1+1ATGDkEXkclR/Q9PDcc1PRegU0TcC6mCJj3rJV1saCb79S7qhRwtxRXIfFCZM1liHyVUyL+Eov39NRFC7ur4X5z8PUwUf5h3HBobzgxbWewDsmCMV5t3WWCx8odLr7QPW6jAgXUCUzOJospXIt28oFWYBmH79lo8xgzOjbLfbFFCDGpjVAX71kMIYvLl5xcdkQmZsRe44n7ez2BItPkcgTGxKn5CepbBoEs23jzfkvR//+ha983ga9i7jiedpWFNsHN9nVSv48vW+UqSmYNdVE2PUEnBA4MdoVF1x3HWjm+gWORnlWDYoSsgQSMkhjnKSeXCH8H3Pv9DxRnwhNV8u68Uel7VqKobUp4iI/BnwPgCv+M4J/BzaDBZ3FFSuXvUj9OMn6Nud2qMSXCVgx4wZJ4xEokm5hb6XtbZ0AI6R3SG1KolRfYOCMiwA9ZIvIKKjbm0ghoSqmpDvPFsdneUKdN+rJMnEZn/VfRkGeZV08ka+9P+af4kF7z1OFbc+6kTnDRW2zICmpQ8o2DUBdglbqmSV3xlUgUWAznffQrwftCWV+o/
  template:
    metadata:
      name: gitea-client-secret
      namespace: keycloak
    type: Opaque
