---
sources:
  - gateway-httproute

provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-cloudflare
        key: api-token

domainFilters:
  - blackcats.cc

policy: sync
txtOwnerId: homelab-k8s
