---
sources:
  - gateway-httproute

provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-cloudflare
        key: api-token

extraArgs:
  - --annotation-filter=external-dns.alpha.kubernetes.io/enabled=true

domainFilters:
  - blackcats.cc

policy: sync
txtOwnerId: homelab-k8s
