---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloudflare-secret.yml
  - ./helmrelease.yml
configMapGenerator:
  - name: external-dns-helm-values
    files:
      - values.yaml=./helm-values.yml
configurations:
  - kustomizeconfig.yml
