---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    client-id: AgAnoCWQGCPbMcrSreJPTIRJipCOtdhrMkrIRmKpZBgF3Az6JPx5lBkLXg+t7l5oI0My0Iw1ysqbCRzHkEvjKGIavvgYyF8mtcI5JJp5ZJ70sggz6gGGIG8avYBNJtGyw4eW+kf4lI08IB86+FVjEn8V13C+srRB5Ok7wd34uN71oFsWCZRwI1PL0zd2rlQx+1KJoMp32US/XomIdVtpePxpxlD6e77UqU5/Wq+iWVol7lVKLGWOTFqZdFOU6yHDvC313t5J5T3gBavtv1y5Jth9PBl2RD954kOYJS4bckmqbgmrdVii5U0y0G3zCR+cEP0PbpvDOxldrQmvGLPjCdeiL0NiWIk3kE8FKsppKD6DmoYybiskMlhMbwhIamNL6nDm9TVhutmnhCq6e3hxFssaWNrFFNhcIDs7tYtO1IfbMRM1SuudNAl3xg5Rp8jrHi2DdaME1FiwHIDAXkPRweCCz9rNIzvR/UadbF6/UQZeTt7CEtd/Op4aSOgY5xKnxfdn88+ix4JQNKNGym1NGEmHHMkAHcr2qxrsrybDilGZ+JDUTVOcwfB0SI7MOp3BBqeKgb91RIXh5Cq6KEJPGpRNRkGwwnjoWY2mCGJI9CeCHUWOtNicJcH1HrRb7AVnHb/fiVmvH5geJWKsKLLd0XF0QWo46hdAkaJMfCeE5i4xDE2GmZH7bp+X6c/y2bb1QpKB9RhL91EwdpeaeIhoAtfxMQ==
    client-secret: AgBVyuq3YRa1Pu4iTQVRyNEgmcpg6rwpSyucVf/aNz7MTxdhNJ5bc1UlfKeh6sA++Myb+A4LpK6aJaNwXngSEIJKIGlPeG0oylZhcR/itTfg5PTlkiJTaJnasn/3QBcYogLg79IcKtnVGl7wWwFzEq6Wop7yyysyub1X5CXe9WPT2O94v3ek3KQwSzaZB0NoDi9OO0abl7TVbRmhrQKMNRvebZwkoh0Q9W4rk1AqEPN2OOICDhxmNO+cn4qNL9/pzKfQBQ/jU9TR00jZxNr6k7NCNxkwLYPRI3GS8yDU9PJHmRuckFpQ7c/2bmn6tcLNm0Q9iY+1P+sTTkKNO3JN31xRH7ugZUFcxd6AljIoz6yQvMP3PISiQmpg2eOy2lpy0fLvA21GhiNIr2f1ZM17XZsKZJAvXj4PKaGc8xKfLMLX3uK+xmgaQ5p3NltmXqtPhDhD7QshRiFGyDVEoxoY2iVwxly4mW7BIyfZfQgSyDZfsLabUihywx5aLajWY5T07vbNukkOhjThGNCwBtCvAhoX5v0FEOgLidZDU5YBvL+PxLHSclDZGk7VHLARPRAUgLamScBUVYpa4FzomBiPBOuvzcKT7VO+1ulx1EKkS2Rp7ke37b+zMQ6yJuqVAMQwPxSV8agY5s+FiIMLYNQyUAU9cZRR8aXkS2i7+uCEDQxDl1+7LSCFUp5K39/J26DJV9UlcqjucS6DRD25EMLoXFEwtdrW2wnAAc14TSYZTDCs6YFAM1fNJakT1DGze8XGfPie584whdGbtMT4L7csTYy4
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
    type: Opaque
