---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    client-id: AgCtHST0B5ahUPEvdRq52xsf4pHxw4MUzY5FVm6YFeiS7g0lNuv7PsXPAsEeH9OXHkU8aLhLpQ842YLlzmyA14HhkjJz+z3Js2PidsFaEKbAKNV1usjS/L4qd4aAmAdFfrqynRClDLu4MJh+Y8Uuqw1dVmTNNNOhoebbVZyC+eXTgiHAaR6eCClkYUtLzNkFsT1BbJ2KwdmtUPdnSJftALfRPVIoxhd+qOMCvrWiirDVFbEH3TjtBnYmgGtF9vHNtgwTcC0+68jX/JjUB+OYdwWj2zYBpP5saLH+VsUyuevrAghy+EZvXcB/258x6mFAYQ5LfoAg624Z1Nn1IqXpgdsBjtaBgp6TGkRS07MxvWGWajgqoq24/zmweqfmysmgFVPgqsIpx6Dz8zNp7lSoPfBpLJHgHyCtPBZxojTKV5A8Bx2P5AtdLCWWtrOdv5SSe+Z//EpTV/M9xoGV1g5EOft4iAvYv6LcEIh2e6/cycq0Qai2DduTqYu90RuXLg2+VwzXDXdJtMXNGoAjJh6S1iDBsiTldYsn6yhvqpR56JabL2Fq3c8TcKXuDeTBVIvT4dEwnVbtytlRB3ckzM0zjfUpNltbfP6nTy3IOibS7s4QEJYaZ/0vH234XkStWY+8kMeLTnS12pQFcgp/BbGdnChsObEwM8OjCbABVHHMis1KdqrRPFuv4wwVzbgubb+OdE6vHVIRK5ghqG1BEU84pVxcDA==
    client-secret: AgAzUaxDcBtwoXV7zITEKXUPDUruP5pfL7WrtASpIG8QU2VKozX2Nz1nqDDKR6hI+moqPUVd6vk/JtUkqxKMho+K5Ycjm5abmqXIC8zq+eOIjIPwTqJ/lekw6kPFs5ql1skaO+tVV1pf0JUHX2aP1mQhcH0nSiArmh+eqc846tUQD0nNyDe9yoX/Ny60VfS2jmMb7duoGb7qJOJ4wM6BgSnq+/TF3pf9DcWdVUZ0Ovny60z/PAaV0jGLfaSnHrGlHUg6BNiMwe3oPqj6oh7KMzKIJPxvqi9HpH3cXtFJF4sjw2/JkM7XP2B1PAuy8+ztLI4lQJHqz+tHoDilQS8xLu0gf6QkNZMg+RfprehL0vfTdFomFQ5oYSyNcwwAw0gAzaLqY6i7QFizqMKx52ZkinRdWD91ztyLfyAOcvRcCMEzQWcl6tOoQ0GZ2dvFc0GY5cm9GKbb26Z1Wc6fLV5PftRsMU1JEB5JOECzyzhYjbm+6UgZF35zP4Jy0SwcTgnzQRJYh8spdwomOO8c5TAXn8OIfvm208Y68lJu1sQuAdiTFIlO7t1Xn5tD0oSnzWS8w/xPp3lgjHpk7ThAFgd3vggnYTQShSaEZYQ+iB39OEC/9hb+VX16248etoKzcOsO23+r+AtUXu4NpZXHpnJEiKO+ZOY4h+uSmZ2m/pi9frvzM8uA743B29lNsTHZqWcT4NFu66OmyI921Xktn1F1AXX/0rJ13iPzOQsle79AvqgUBH5CsxpQWz+ZM20M
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
    type: Opaque
