---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-smtp
  namespace: keycloak
spec:
  encryptedData:
    password: AgAJwlzufXMzpqQe5URJ489CIdhNOu9G+0EStO6gjlFPbjrE0aUiQIqR/tjH+HyWkk7ChJ+ujIT3A8A0Sax0y5TZdzI/RS7bDvjJnW5tYzeUhJhL5hJBpGxMxq1+a7imHlYG93gvFTZ6GaqGCRLguSm5OcHKfdMv3JA5kyRqy0HPGqfLqDwJ0s/TEfBY1BNwXBDJfiI0iS2LdO7rTxgfTiCkDiCyvUCasA1TXP6szczsHQ0ZoCocO1dl4dmQZU4mB7CjgtGaIXbfS0gIa72Sw9jfeULRlqcuCcWmRueAU98aeJVBV7ZNml8wsKrun4OumeYIUA4Ep3JbX30UHzYF4jccEqKYXQOg/IBXYcW+XHqqt4qu8StW3D11CLsk458RfBJgrJBmutE2K5bxnCE8Jgp3tc1K5iJxwZK56hQcO4T+6KJ1vpE/5F9hP135Hh/DnIabbZE9qw57SWXRO3UYmcaRx/Xs0rinZLf9dEZ9FrMFbP4I5S7CMK/1ffmfpKVqWHxl4NGBQtg/0HPOxxW7FPQwAnIERxra8jDsrzch9YpbYo7Oe9vumlzlbtoKoCk1g2NZ1R5ZHjTwRUaOFjInLpmf/j10zXf3KwHwEkYvskMaj8/vveKfNbpkEefXqDWeeUlSAFtsUcXMLq1tUGxOyEdc3ddlxAGORx/EsFb+za2e+SdVw+NMvS/WrJ+CBEohinGBsL3VuDirxr64UoejY0wAFFp16tyR
    username: AgCOrWWjQCbfb7LMWm4xWJYKiIG0rDS4HdpvTqvxVu7I6gCgdc/ORIsGrTv85GwqR7kz7YiJebLiC/nS2rPwI90n4hn7RIXoiLN4qesEuMQzeHhduf0IX1dYKe60tdcPpy77q4WFJvaWGtUUjdbC+SdPzcjCdwTzH2o0Ij8kKY6K6DN25tveSdtwvE8diSCh6nazbtbhjl6qn4SNJ38Fn4DljA7ZjdVWpEnMAZLme1SjB7v4lUKAcm1LddGqMCiW+mc9jHUUHNM7V43xyWgGQ/WrbUdkpSozUBmX8eiimidxWSy03Xf9+m7Ob1VlPu/7+2plnTY2uDEpAxtTtsOxFUkyz08SDNpL6NKOrdyXGOQ2cntvMKvFRRia9CGUvJ5duLJ8/Ep9M47Ioaeijcr8QCWHsCN/YRaYh0debpR6E1+zJqtzY517y2ZyyeZe1wVADFTmy/6JyWn6Fnudwk7SqP/rA1kLoupFFjFho5TD7G2U94TYjSAAeMN/H/npYBhy0O/IDQNFlZFrEHeHAGmmUc4RWF17oXJflgEWx6/9/PPdn4f6+XMovFLIV+CN4W3MoDAjwNquZTX6acTQxzUE4JAr1p+k2vQVVvj5y8+uTfPhBfKggfrgVo7UUsbFAq71f7ay3CUPKg4laHqvDHbSDdSNw5OG4Tm2XAxD8niO+x6pUcMcwAiJjOnLO87Mw7Mqqd5rLaXMDI1YiZ58uh1QyckegkU=
  template:
    metadata:
      name: keycloak-smtp
      namespace: keycloak
    type: Opaque
