---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app k8s-cleaner
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cilium
  path: ./kubernetes/apps/kube-system/k8s-cleaner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-cleaner-rules
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: k8s-cleaner
  dependsOn:
    - name: k8s-cleaner
  path: ./kubernetes/apps/kube-system/k8s-cleaner/cleaners
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  timeout: 5m
