---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-app-secret
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_SECRET_KEY: AgAaF47Pgm35z33yAP0bYVIErfZJpz1Dv01VXEucW9y5GBx73WIf4Vtu5kzE7wOxfntmPbHRNxpe4hsEzYKnq8V0zFGskeLK4iuwA3dhcPrqbu8IOcNXjVhZ4NmhLv5CtxB6btuLM+J2VJpKimfyCRx6vo1lAQ29034AsFYjc3aQIR0ksEBm5xmznaaNeGN2LmFcyEYiji1AYr2WkxS7Okncq+q2Ubb38f1ruCfe10+/zbv8Tymtwsa5N/7T4Ba4cs98KrMzCxE8QqoZD888iiYnX/4/ruxCVeuOtDTro9cnKO96zx9M3UkHTGL5GyEstRjhf8uibFbVgxpL3SwWWdLle0bcSTz9OU1nC9GhKVfFRWHbZmj6S/5Phi0joaF483UUZzhc2zgEOkZkuFMo46TBXz5N9N2v2tzhlZhyNC2h7n5IKe0DCTR87gOPiOcSw6EajcuEK+SHsyJnhHrr/pIs7yCOtxMS6Xf5Wj2d4KvhAF8Rr/aCMD5WMETlprIz+fqV0Cmfxr/pvjspsJj6i769ZdnEwg8JdT719JhyxsqpBhiIFFWQWFykYBtt7+KBW2BLECzrQ8rTqpee5QkH/G0pFr4vhjJaQcCpeKzQiy7n/ckLpaZ+OQwrMCteez3JN8pQNRi5VfUkW8kUSwtH1a/PhQYfQd2zzbukd/bLTh3idG60t8wF9e9TKHfTK9cLebikaidnBYMk3+LlYagBeulKQ539m8m3/oD8Av8KmHIB2JEscDESOGXh3Qb4/Vf6rj4uDw==
  template:
    metadata:
      name: paperless-app-secret
      namespace: paperless
    type: Opaque
