---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-app-secret
  namespace: paperless
spec:
  encryptedData:
    PAPERLESS_DBPASS: AgBM2Uw1MFJx1pme1jGbF3Amp/0WT5WedWjoGCIeua8eP87Qp7Xdk2UnVBu0U/VnsaIPpopElJABZaW1Fmg48JSnDYTyC2AS2h0qvxykAAg+S3Ev8ouKGSRfZeGuz7UE/cJtpL/zFmakmVFIoyJJfJXXok+Mt74ozFo01zaSnMHhviv2Zy+C+d5axCKiRYfP3SR8eCIT5ts2ZNivubxCb0OGuxVJwOI+ZoZlbrZGoA1h4XpbAzmUCEPeO7jzfSW1qIUu40GYLjY3e8enJGzrtloGUEchat/i5it+TV0IH0oKQ5MYwVFYtCsSKt9jCp6IAPhVmauwB9pRnK2KBXpHMOipPvIl8ENGWoYq3ggYczeNS6rBaL7Bxe6W6f+j5oAgBEOltM8u2tfQkWRwNnwsl1nPSAGvJF8Wg5EdWHrfDyAz1LQY857sOC9hPSzFZ5qmHfmwkGgmHhoRsyPSf1VPoEHceA5YQAlpekFvQL8GvxIPqixlolXkZG/Ba7iTR+I+MlCtWdRkoXQtfQfIJyEyRKScrW84l8youx+zLW6Uk7OhmqVQLMaebeQZO48OSjF9PH3ZpEIg2LaUKAM7OL8STa4rmm38jVUdYe42GSeyOSEHxJUtYHUeF25ys1V5HJIS6E10ac6UqpBrvs0lmUC5eKD56jkcqneoX6ZyTYv0vdYzmjabiD3T9nl0bymzG+Wh8CbGOaheIY9HedpvbNc=
    PAPERLESS_SECRET_KEY: AgC4m1VsrjY3vLTH691IvRxQCHwOK4lPD35WJfE86A0GV/Dwodk4R6wka4adomCJp/Q7A7fT0QCUMQbNlAolm2gcMPZsm2B9vOw8orFDfMab09NnxV6I/f51qKbxfdt1UynX4WgXD6EafQIuT8OSdfyfWyUyXizsyXonFoCJxG5I4B/NYtMMTEQ+jpZTMHFK+TJiEztv+hfcj6nBgAPytPkV11oUqNq8HUDE9X6d88ew1F5WQvDy/wVNXkeK8ksKt98pPrFsrX9ky/8+07tGI8MwSSkqvOv8w7tsCaXbbIUuM+RiHIKWxC97s9XM0IvgYVrNNE3DpNi/qorifq/K301G/8soUsXdGjbpDCIV1Iwd6lmW+2jzNPyQJ2mvvNVbU2G2FmUhM9vHwRVkxjzLjtR6Oh1S3soV9PYaAh7QtqHFoOfITb7fOyAHhaIz83vjLeeW4hsC6VBPvxXZjxy+iTagsLmg4e4SsIaVOYEERJXz/Dp5G7RA2Lir58j2OAjSwdgS/8h/I4PmZOAyBDJmWgbrO1i0SLL03UtW7xhhoqGNTW47iBQqLeaakbtjTDlQzi9Yw7YNLbbwTZJ7zwT/mOkR7DHylMv3Q008hnUxjJYcY0wvh1zFZy2y4OmKwZQANMP8ZUOp5stsPubsj32hnT1pGbmAHh9/FyX2yMtTVc+RLHKBX1P6G01wbHVfIAlbzf/EcfbwLEqU6E4gcgWiwmrBpuIVPTHx3Mrb0ssv9tmwSg+zLnUFGPGaG4S4bzRT8HX2Bw==
  template:
    metadata:
      name: paperless-app-secret
      namespace: paperless
    type: Opaque
