---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secret
  namespace: ai
spec:
  encryptedData:
    OPENAI_API_KEY: AgB8LVtwQYaw3EGWk/rEekf/hpAKXZ+k81pyzAnPZXtgIHktuXCB8hyambnj4jW4cB+qkzSC0DGHROEkyKMdUp+/OvhXcd9Z4W4+KdamDSUUdH8j+fwcEX2UcI4a2OZoYOUSKjDdHkHn2AFFYXhDG9km1RHG9iAviYQ/IduxAtE1Bd2oRUsbH1APLibIUTW+sck+M13e4Vb3J9Wauzxf4IZgMoH+rTvtZTRgaa/fD3U+DeivVX62PW0qtV8RCqdcZHIrvr/EM9zvzcg/lRfTr76qWSKT1MHZsVrOocDc646yjsJ4DQ/raMHE1SPUxGQ714Wd8dEbE0MNBwr4GMvlfRx2wxgbQ5tUzyScBExK95xRzbAxELQjjtSrpwmN9lpQXtCtHydfdAj7bJpuJHEaFVlsrhf9f6ffAcq9oL+aIkiN9SALvBTPxjE53I4/ysOq4mSfun3oNRUczIaI+lWJyEWrH7bDMQGlMfD520lTmW+ONr0H3tNoySPtdZdfnnsHQG5ud0FELBbP4wzOhjjpXbvliKN5TCbyhTbQdOkna16IJRq3BEcxkwjv3Ck40bULHRXEHeEaYaJVwKn9Zty/8PVnpeGe9BeUS6tfnRMJ0oaqc9vfmGex3HC88rcajcZgqosKLpRkiunPItG0RQ0r1kO9mUY+8MTJH2rHRNh61dnxo6Y28J5rbVswaTAX1nZPr7sltHht4jj+uD1ZWF5EmDt6g0QeWjFUfk7ODjWtXyszYA==
    WEBUI_SECRET_KEY: AgDPxoteTtj8RCluZkmOVITgeU66j/n9BIMvzOFWWdHPyOvMjcNPG/7Qcp3v6RC1WkavV82LZ+mSlvGR2vUIGs8Mi6evMtfs6ZsE+uTotcR04U6n82wmnFpHNXT8CbahYqdpqnAaJp3jfbwHbRM5c4nIHzV2pgchupvQxBFTd+SsNk4WzuH0sjYdMtWv0Zw2xcjGZWhZHgEIX4pZqDfeLRwfniIYNXRTn5ieqr62vfk4Nuw2zm6WbytAKPRLxMjdkvpND3Lt0bfryej+ioS/heoAx3lXGDS8e7ki4J8Ysq39vjVkLTIaIngAiMDiq3F9oVUhfbXqvBfcH0kjUgpOb2uUdo/aI5zAbLdFp3dxnyrYUkGlBw1Yne1WXY42NdkPQ9SLu17UdUb7DtxlychuDCkYLW78g6hBwnSLuMxoELgi19M3TSlZDMw/JYV3MH2OwwfPqSq8tAvZkC0mOR9xOjUh3AnRomNEZOGHLsyBubwv1aKK9r/vDKoXE3ZNzQphIYElJ4FQPhMaCO/vspUOfSNv2X9GozFSiPEu0FrbwdI2E+Nqp7KYIqWOO0UVyaVwImMMQrtW3hgUVNM4CXYpbL8gWmDjFFlAe1tCqCyHg3r+VYA/TOd8uuUH7USnMrTHAIPRfsbsjPHol2m0NAXlOXJEU7Tpvr+SAyl8lg6kElicIM2ty+osun741KhqIm1kNngdz9CYnP0hzpPWGE3pxK3EW228iw6H6KEN+/VS6Wf1qH7JaopviEoDgsuRxuk0pz8=
  template:
    metadata:
      name: open-webui-secret
      namespace: ai
    type: Opaque
